Fix add folder to collections being broken when logged in
hoppscotch/hoppscotch pull request #1299
Opened 2020-10-25 13:37 UTC by AndrewBastin

This PR intends to fix the issue with the add folder to collections option being broken when logged in due to improper vuex store updates.

2020-10-25 13:38 UTC, liyasthomas approved these changes

2020-10-25 13:40 UTC, TravisBuddy commented
Hey @AndrewBastin,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;hoppscotch&#x2F;hoppscotch&#x2F;builds&#x2F;192617076">View build log</a>

###### TravisBuddy Request Identifier: ab1e1330-16c7-11eb-a761-09290313622d

2020-10-25 20:58 UTC, farhan-tariq approved these changes

2020-10-25 21:08 UTC, farhan-tariq requested changes
Adding a folder to a sub folder does not work anymore. It just adds the newly added sub folder to the main collection instead

2020-10-26 01:04 UTC, liyasthomas commented
@farhan-tariq I just tested adding nested sub-folders on deploy preview, and it's working fine. Can you tell me how to reproduce the issue you've mentioned?

2020-10-26 01:13 UTC, farhan-tariq commented
> @farhan-tariq I just tested adding nested sub-folders on [deploy preview](https://deploy-preview-1299--hoppscotch.netlify.app), and it's working fine. Can you tell me how to reproduce the issue you've mentioned?

My mistake  it was the UI that misled me to believe that. Yeah It works as expected.

2020-10-26 01:14 UTC, farhan-tariq approved these changes

2020-10-26 01:14 UTC, TravisBuddy commented
Hey @AndrewBastin,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.com&#x2F;hoppscotch&#x2F;hoppscotch&#x2F;builds&#x2F;192657179">View build log</a>

###### TravisBuddy Request Identifier: 9a22e180-1728-11eb-9e63-49d4a1c7c4f7

2020-10-26 01:15 UTC, merged