Sync bodyParams and rawBodyParams
hoppscotch/hoppscotch pull request #1562
Opened 2021-03-24 21:02 UTC by Reflex-Gravity

This PR fixes #1435

I have added the option to sync across Request Body params and Request Body raw Input.

I believe that even though the code works, I might have not followed the code standard in this codebase. Let me know if I have to do any changes.

2021-03-25 14:50 UTC, liyasthomas approved these changes

2021-03-25 16:49 UTC, liyasthomas commented
There's a active <=> inactive toggler for key-value parameters. I guess we should respect that before converting to raw body. Just check if the item in key-value pair has `active` property. If there exists an `active property, check if it's true. if true - convert to raw. also if there doesn't exist `active` property - also convert to raw.`

2021-03-25 17:04 UTC, liyasthomas requested changes

2021-03-25 17:04 UTC, liyasthomas commented on components/http/BodyParameters.vue
> +        this.$store.state.request.bodyParams.forEach(_param=>{
```suggestion
        this.$store.state.request.bodyParams
        .filter((item) => (item.hasOwnProperty("active") ? item.active == true : true))
        .forEach(_param=>{
```

2021-03-25 17:04 UTC, liyasthomas commented on components/http/BodyParameters.vue
> +        this.$store.state.request.bodyParams.forEach(_param=>{
Checks active property before making raw body from key-value pair.

2021-03-25 17:36 UTC, snapeur82 commented on components/http/BodyParameters.vue
> +        this.$store.state.request.bodyParams.forEach(_param=>{
Yessss,,,
Love un marci

2021-03-25 17:39 UTC, snapeur82 commented
Yessss,,,

Le jeu. 25 mars 2021 14 h 04, Liyas Thomas ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In components/http/BodyParameters.vue
> <https://github.com/hoppscotch/hoppscotch/pull/1562#discussion_r601678110>
> :
>
> > @@ -184,6 +176,21 @@ export default {
>
>          fileIndex,
>
>        })
>
>      },
>
> +    updateBodyParams(event, index, type){
>
> +      this.$store.commit(type, {
>
> +        index,
>
> +        value: event.target.value,
>
> +      })
>
> +      let rawParmas = {}
>
> +        this.$store.state.request.bodyParams.forEach(_param=>{
>
>
> ⬇️ Suggested change
>
> -        this.$store.state.request.bodyParams.forEach(_param=>{
>
> +        this.$store.state.request.bodyParams
>
> +        .filter((item) => (item.hasOwnProperty("active") ? item.active == true : true))
>
> +        .forEach(_param=>{
>
>
> ------------------------------
>
> In components/http/BodyParameters.vue
> <https://github.com/hoppscotch/hoppscotch/pull/1562#discussion_r601678777>
> :
>
> > @@ -184,6 +176,21 @@ export default {
>
>          fileIndex,
>
>        })
>
>      },
>
> +    updateBodyParams(event, index, type){
>
> +      this.$store.commit(type, {
>
> +        index,
>
> +        value: event.target.value,
>
> +      })
>
> +      let rawParmas = {}
>
> +        this.$store.state.request.bodyParams.forEach(_param=>{
>
>
> Checks active property before making raw body from key-value pair.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hoppscotch/hoppscotch/pull/1562#pullrequestreview-621367425>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATLDRZTXFXUUUBJ23FURKMDTFNULBANCNFSM4ZYCCWWQ>
> .
>

2021-03-25 19:50 UTC, Reflex-Gravity commented
> There's an active <=> inactive toggler for key-value parameters. I guess we should respect that before converting to raw body. Just check if the item in key-value pair has `active` property. If there exists an `active property, check if it's true. if true - convert to raw. also if there doesn't exist `active` property - also convert to raw.`
> 
> Also `delete` and `active <=> inactive` toggle doesn't seems to be updating raw body since it's tied to `@change` event listener which only activates when there's a user input in input box. Need to add events on both active toggle and delete button.

Sure. I'll update these too.

2021-03-30 23:40 UTC, AndrewBastin approved these changes
I don't see anything generally wrong. I am approving this.

2021-04-03 08:50 UTC, liyasthomas commented
@Reflex-Gravity let me know if you need any help with those pending tweaks.

2021-04-10 07:00 UTC, Reflex-Gravity commented
> @Reflex-Gravity let me know if you need any help with those pending tweaks.

I have done the requested changes.

2021-04-10 08:03 UTC, liyasthomas approved these changes

2021-04-10 08:03 UTC, merged

2021-04-10 08:14 UTC, liyasthomas commented
@Reflex-Gravity thank you.