Feat/override contenttype
hoppscotch/hoppscotch pull request #2191
Opened 2022-03-22 21:03 UTC by anwarulislam

Closes # 

### Description

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### Additional Information

2022-03-23 17:21 UTC, AndrewBastin requested changes
Please look into the comments for some fixes.

Also, I am not really satisfied with the behavior right now for multiple reasons.

1. If I press override and a valid override is applied, it would be cool if the button indicated that, the content-type is being overriden to this value, instead of just being an "Override" button.
2. If I create an override (which adds the header), then I remove the "Content-Type" header, clicking Override again doesn't do anything. Something would be nice there.

@liyasthomas can you chip in on the expected Override button behaviour as well ?

2022-03-27 07:53 UTC, AndrewBastin requested changes
Please look into the given comments.

2022-03-27 07:53 UTC, AndrewBastin commented on packages/hoppscotch-app/components/http/Body.vue
> +const emit = defineEmits(["changeTab"])
Vue for TypeScript has an alternative way to define emits and props which tell the proper type signature of the emit functions.
Please check out: https://vuejs.org/api/sfc-script-setup.html#typescript-only-features

2022-03-27 07:53 UTC, AndrewBastin commented on packages/hoppscotch-app/components/http/Body.vue
> +const headers = useStream(restHeaders$, [], setRESTHeaders) as Ref<
The type casting here is redundant.

2022-03-27 07:53 UTC, AndrewBastin commented on packages/hoppscotch-app/components/http/Body.vue
> +watch(
Can't `overridenContentType` just be a computed property ?
Also, during the rewrite, try using `fp-ts` to build the result.

2022-03-27 07:53 UTC, AndrewBastin commented on packages/hoppscotch-app/components/http/Body.vue
> +              ? 'The Content-Type is being overriden to ' + overridenContentType
Is this i18n friendly ?

cc: @liyasthomas :eyes:

2022-03-28 08:37 UTC, liyasthomas commented on packages/hoppscotch-app/components/http/Body.vue
> +      A.findFirst((h) => h.key.toLowerCase() === "content-type"),
`overridenContentType` should check the `active` boolean value in headers entry.

2022-03-28 12:16 UTC, liyasthomas commented on packages/hoppscotch-app/components/http/Body.vue
> +      A.findFirst((h) => h.key.toLowerCase() === "content-type"),
Please use `findLast()`
```suggestion
      A.findLast((h) => h.key.toLowerCase() === "content-type"),
```
Last occurance has highest preference if there're multiple entries with same key.

2022-03-29 02:38 UTC, liyasthomas requested changes

2022-03-29 02:38 UTC, liyasthomas commented on packages/hoppscotch-app/components/http/Body.vue
> +    A.findLast((h) => h.key.toLowerCase() === "content-type"),
```suggestion
    A.findLast((h) => h.key.toLowerCase() === "content-type" && h.active),
```
`overridenContentType` should check the active boolean value in the headers entry. cc: @anwarulislam

2022-03-29 04:23 UTC, liyasthomas approved these changes
LGTM.

2022-03-29 04:23 UTC, merged