feat: added developer options to copy user id token
hoppscotch/hoppscotch pull request #2204
Opened 2022-03-25 18:06 UTC by nivedin

### Description
Added a feature that helps developers copy user id token directly from the app.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2022-03-27 14:35 UTC, AndrewBastin requested changes
Please look into the given comments.

2022-03-27 14:35 UTC, AndrewBastin commented on packages/hoppscotch-app/components/app/Footer.vue
> +              @dblclick="currentUser !== null && showDeveloperOptionModal()"
Minimize logic inside templates. Can you move this into a event handler ?

2022-03-27 14:35 UTC, AndrewBastin commented on packages/hoppscotch-app/components/app/Footer.vue
> +const currentUser = useReadonlyStream(probableUser$, null)
Use `currentUser$` as the stream instead.

2022-03-27 14:35 UTC, AndrewBastin commented on packages/hoppscotch-app/helpers/actions.ts
> +  | "modals.developerOptions.toggle" // Shows the developer options modal
Eventhough we have defined this action and a action handler, we don't actively have any bindings to it, so lets just remove this action.

2022-03-27 14:35 UTC, AndrewBastin commented on packages/hoppscotch-app/locales/en.json
> +    "copy_user_id": "Copy user id",
Something better like, "Copy User Auth Token". This is not an ID, its a token foremost.

2022-03-28 08:16 UTC, AndrewBastin approved these changes
LGTM 💯 

Please wait for @liyasthomas's clear as well.

2022-03-28 08:43 UTC, liyasthomas approved these changes
LGTM.

2022-03-28 08:44 UTC, merged