feat/unsaved change popup
hoppscotch/hoppscotch pull request #2239
Opened 2022-04-06 16:55 UTC by nivedin

Closes #2207 

### Description
Shows a popup when there are any changes done in the current request (API, parameter, body,..) and clicks on any other collection.

### Checks
- [x ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x ] All the tests have passed

### Additional Information
When a user is working on a request and made many changes and accidentally clicks on another collection request all the changes that have been done will be lost. So to prevent this problem this PR adds a function that triggers a popup when any changes are detected when the user clicks on another collection request which asks whether to save or discard the changes.

2022-04-11 03:22 UTC, liyasthomas approved these changes

2022-04-12 13:25 UTC, AndrewBastin requested changes
Please make sure your type checking is working correctly, there are so many type errors in your implementation. Make sure you have Vetur (VS Code extension) disabled/uninstalled and Volar (https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) installed and setup properly.

Also, rename everything named with "API", we are not working with an API here, we are working with a request, there is a difference in wording. So you will have to update couple of variables you have declared, the i18n strings added and rename `ApiChangeConfirmModal` to either `ReqChangeConfirmModal` or just `ChangeConfirmModal`.

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/components/collections/my/Request.vue
> +  saveCurrentRequest(saveCtx)
Type Error over here.

`saveCtx` can be null.

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/components/collections/my/Request.vue
> +    // TODO: handle error case (NOTE: overwriteRequestTeams is async)
This TODO is implemented and can be removed.

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/components/collections/my/Request.vue
> +const confirmApiChange = ref<boolean>(false)
`confirmChange` is a better name as we are reserving API naming for things in the future.

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/components/collections/teams/Request.vue
> +})
```suggestion
const isSelected = computed(() =>
    !!props.picked &&
    props.picked.pickedType === "team-collection" &&
    props.picked.requestID === props.requestIndex
)
```

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/components/collections/teams/Request.vue
> +})
```suggestion
const isActive = computed(() =>
    !!active.value &&
    active.value.originLocation === "team-collection" &&
    active.value.requestID === props.requestIndex &&
    isEqual(active.value.req, props.request)
)
```

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/components/collections/teams/Request.vue
> +const dragStart = ({ dataTransfer }) => {
Type Error!

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/components/collections/teams/Request.vue
> +    requestMethodLabels[method.toLowerCase()] || requestMethodLabels.default
Type Error!

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/components/collections/teams/Request.vue
> +      requestID: props.requestIndex,
Type Error!

2022-04-12 13:25 UTC, AndrewBastin commented on packages/hoppscotch-app/locales/en.json
> +    "confirm_api_change": "Are you sure you want to change the api, unsaved changes will be lost.",
We are not editing an API. We are editing a request. There is a difference!

2022-04-13 13:25 UTC, liyasthomas approved these changes

2022-04-13 15:22 UTC, merged