refactor: realtime log entry revamp
hoppscotch/hoppscotch pull request #2240
Opened 2022-04-06 17:34 UTC by JoelJacobStephen

### Description

Revamped the log component and included a new component that handles the UI for each log entry. Changed type definition for log entry data (removed color attribute, added event attribute and refactored the timestamp attribute).

### Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

2022-04-22 01:44 UTC, liyasthomas commented
- Copy button on the log entry is broken, clicking a copy button makes it invisible.
- The entire hoer logic should be removed from the script setup. Instead, use plain simple `CSS` / WindiCSS classes. Pretty sure there are classes like `group`, `group-hover` etc to cover these use cases.
- `SmartTab` logic inside the expanded section seems wrong. 

If we're merging this to `main`, this PR should accommodate the following features as well:
- [ ] Toggle button to enable auto-scroll to the last entry.
- [ ] Button to delete all log entries
- [ ] Virtual scroller [optional]

2022-05-05 13:46 UTC, liyasthomas commented on packages/hoppscotch-app/assets/icons/arrow-down-left.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#eaaa45" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
Icons should always have `currentColor`. Do not give fixed colors, instead use a computed class name to color the icons where they're being used.

2022-05-05 13:47 UTC, liyasthomas commented on packages/hoppscotch-app/assets/icons/arrow-up-right.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#38d4ea" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
All Icons* should use `currentColor`.

2022-05-05 13:50 UTC, liyasthomas requested changes
@JoelJacobStephen, cc: @AndrewBastin
- [x] Fix broken "delete logs button" on the `SSE`, `Socket.IO`, and `MQTT` sections.
- [x] Remove fixed colors from svg icons

2022-05-09 19:12 UTC, AndrewBastin commented
Looks fine in my end.

@liyasthomas please review and merge.

2022-05-09 20:32 UTC, liyasthomas approved these changes
LGTM

2022-05-09 20:35 UTC, merged