feat: Shortcodes UI implementation
hoppscotch/hoppscotch pull request #2321
Opened 2022-05-04 07:43 UTC by nivedin

### Description
This PR introduces a feature in which authenticated user can view their created shortcodes and can delete or copy them.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2022-05-05 17:23 UTC, AndrewBastin requested changes
Please look into the given comments.

Also, please maintain a single naming convention across the codebase, for example, the backend operations define it as a 'Shortcode', not a 'ShortCode' or 'Short Code'. Different naming styles are being used throughout the code here, normalize it into a single style.

(it should be Shortcode/shortcode, not shortCode/short-code/Shortcode etc.)

2022-05-05 17:23 UTC, AndrewBastin commented on packages/hoppscotch-app/helpers/shortcodes/ShortCodeListAdapter.ts
> +    clearTimeout(this.timeoutHandle as any)
TypeScript is raising a valid point here, what if there is no timeout handle (for e.g, already disposed or when not initialized). Should we call `clearTimeout` then ?

2022-05-05 17:23 UTC, AndrewBastin commented on packages/hoppscotch-app/pages/profile.vue
> +        toast.error(`${t("error.something_went_wrong")}`)
We can detect exactly what happened here. For example, if its a network error (see err.type)

2022-05-05 17:23 UTC, AndrewBastin commented on packages/hoppscotch-app/pages/profile.vue
> +        refetchShortcodes()
Do we have to refetch the entire list again just for deletion ? The adapter should handle deletion without refetching everything.

2022-05-05 17:23 UTC, AndrewBastin commented on packages/hoppscotch-app/pages/profile.vue
> +const refetchShortcodes = () => {
This function doesn't need to exist.

2022-05-17 06:31 UTC, liyasthomas commented
@nivedin this branch seems broken. Please rebase to the latest `main` and update the PR.

2022-05-19 10:57 UTC, closed without merging