feat : UI implementation of Shortcode
hoppscotch/hoppscotch pull request #2347
Opened 2022-05-19 10:11 UTC by nivedin

### Description
This PR introduces a feature in which authenticated user can view their created shortcodes and can delete or copy them from their profile page.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2022-05-20 14:13 UTC, AndrewBastin commented on packages/hoppscotch-app/components/profile/Shortcode.vue
> +const copyIconRefs = ref("copy")
```suggestion
const copyIconRefs = ref<"copy" | "check">("copy")
```

2022-05-20 14:15 UTC, AndrewBastin commented on packages/hoppscotch-app/components/profile/Shortcode.vue
> +)
```suggestion
const parseShortcodeRequest = computed(() =>
  pipe(props.shortcode.request, JSON.parse, translateToNewRequest)
)
```

2022-05-20 14:17 UTC, AndrewBastin commented on packages/hoppscotch-app/components/profile/Shortcode.vue
> +}
```suggestion
} as const
```

2022-05-20 15:03 UTC, AndrewBastin requested changes
As discussed on call.

2022-05-23 16:36 UTC, liyasthomas commented
@nivedin

1. We should provide a `loading state`, a spinner while fetching the remaining entries in the list (intersection observer action).

2. Limit the table's height to a convenient fixed height (~360px). Let the entries overflow within the table's body.

2022-05-23 17:12 UTC, AndrewBastin requested changes
As discussed in the call

2022-05-24 11:49 UTC, liyasthomas submitted a review, later dismissed
LGTM.

2022-05-24 12:18 UTC, AndrewBastin submitted a review, later dismissed
lgtm :100:

2022-05-24 12:28 UTC, liyasthomas approved these changes

2022-05-24 12:28 UTC, merged