MQTT UI Improvement
hoppscotch/hoppscotch pull request #2381
Opened 2022-05-30 08:19 UTC by anwarulislam

Closes # 

### Description

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### Additional Information

2022-06-20 10:22 UTC, AndrewBastin commented on packages/hoppscotch-app/components/realtime/Mqtt.vue
> +const subscriptionModal = ref(false)
More descriptive variable names.

```suggestion
const subscriptionModalShown = ref(false)
```

2022-06-20 10:45 UTC, AndrewBastin requested changes
The Mqtt component should be split apart to respective bits.
These Tabs should become a new independent component itself.

And personally the current UI gives me literally 1 log entry space on the Log component at a time, which is horrible.

2022-06-20 10:45 UTC, AndrewBastin commented on packages/hoppscotch-app/components/realtime/Mqtt.vue
> +        <div
These tabs stuff should be in a separate component as well.
If the MQTT component is to deal with the rendering the whole of the MQTT UI, Tab logic should not be its concern!!

Single Response Principle please!!!!!

2022-06-20 10:45 UTC, AndrewBastin commented on packages/hoppscotch-app/components/realtime/Mqtt.vue
> +  changeTab(topic)
This is going to change the tab to the topic id if one of the tabs match. Okay, that sorta makes sense I think, but then there is no returns going on here, the push will happen even if something matched.

2022-08-25 07:22 UTC, AndrewBastin requested changes
Just some minor corrections :)

2022-08-25 07:22 UTC, AndrewBastin commented on packages/hoppscotch-app/components/realtime/Subscription.vue
> +const QoS = ref<2 | 1 | 0>(2)
Compile time constants should be UPPER_SNAKECASE.

Also, it is better to bind the types of these together.

```suggestion
const QoS_VALUES = [2, 1, 0] as const
const QoS = ref<typeof QoS_VALUES[number]>(2)
```

2022-08-25 07:22 UTC, AndrewBastin commented on packages/hoppscotch-app/components/realtime/ConnectionConfig.vue
> +// config
Unhelpful comment

2022-08-25 07:22 UTC, AndrewBastin commented on packages/hoppscotch-app/components/realtime/ConnectionConfig.vue
> +const QoSValues = [2, 1, 0] as const
With the repeated usage of QoSValues in some places, I think it is better to move it to the `MQTTConnection` file.

2022-08-26 09:47 UTC, anwarulislam commented
@liyasthomas do you have any feedback regarding MQTT UI?

2022-10-29 22:08 UTC, balub commented
@anwarulislam please refer to the notion doc for improvements/issues found with this feature.

2022-10-29 22:11 UTC, balub requested changes
@anwarulislam fix the issues with the tabs and other bugs pointed out in the doc.

2022-11-09 23:58 UTC, AndrewBastin requested changes
Remove unused refs.

Also one helpful refactor that can be done. For the template refs within the files affected, it would be cool if you changed the declaration from `ref<any>(null)` to `ref<TippyComponent>()` (you can import `TippyComponent` from "vue-tippy")

2022-11-09 23:58 UTC, AndrewBastin commented on packages/hoppscotch-app/src/components/realtime/ConnectionConfig.vue
> +              ref="QoSOptions"
This template ref is not used and can be removed.

2022-11-09 23:58 UTC, AndrewBastin commented on packages/hoppscotch-app/src/components/realtime/Subscription.vue
> +            ref="QoSOptions"
Unused ref.

2022-11-21 07:32 UTC, balub commented
![Screenshot 2022-11-21 125314](https://user-images.githubusercontent.com/14091627/202989237-a986f979-fec2-477e-a56a-369e7d868eb3.png)
@anwarulislam can we make it so that the default background color (light or dark mode) is cannot be used as an option for selection when creating a new subscription .

2022-11-21 07:37 UTC, balub reviewed
![Screenshot 2022-11-21 125314](https://user-images.githubusercontent.com/14091627/202991680-9f2a164f-b94d-47e1-ad80-cba4d2495615.png)

@anwarulislam can we make it so that the default background color (light or dark mode) cannot be used as an option for selection when creating a new subscription .

2022-11-21 08:07 UTC, anwarulislam commented
@balub, since we are using a color picker to pick the color when subscribing to a topic the user has full control over it. In either case, we can define some constant color and show it to the user to select from. What's your suggestion?

2022-11-21 09:46 UTC, liyasthomas commented
I can take care of this. @balub, please approve the PR if everything else looks good to you. So that I can review and append my changes to this branch.

2022-11-26 21:07 UTC, liyasthomas approved these changes
LGTM

2022-11-26 21:13 UTC, merged