feat: filter json body response
hoppscotch/hoppscotch pull request #2404
Opened 2022-06-06 08:41 UTC by nivedin

Closes #2334 

### Description
This PR introduces a feature that helps users selectively extract data from the body responses using keywords.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information
Added  [ jsonPath](https://github.com/JSONPath-Plus/JSONPath) as a new dependency for filtering response data.

- [ ] Make the filter method more user-friendly and easy to use.

2022-06-06 09:21 UTC, liyasthomas submitted a review, later dismissed
LGTM

2022-06-06 15:20 UTC, AndrewBastin requested changes
As discussed in the call.

2022-06-10 12:35 UTC, AndrewBastin approved these changes
lgtm 💯

2022-06-10 12:35 UTC, liyasthomas approved these changes

2022-06-10 12:42 UTC, merged