feat: team environments
hoppscotch/hoppscotch pull request #2512
Opened 2022-07-14 17:19 UTC by nivedin

Closes hoppscotch/internal-issues#2 #2429 

### Description
This PR introduces a feature that allows users to create team environments. The environment UI is divided into two 'My Environments' and 'Team Environments' same as the collections UI. Users can select the team that they are part of and create, delete, and update the environment variables.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information

TODO
- [x] Update the store environments when the team is selected
- [x] Differentiate the 'team environment' and 'my environment' variable tooltip UI when selected.

2022-08-05 07:55 UTC, 987Nabil commented
Is there anything blocking this feature? Because it would be what empowers us to really use hoppscotch to the fullest 🙂

2022-08-05 09:03 UTC, nivedin commented
> Is there anything blocking this feature? Because it would be what empowers us to really use hoppscotch to the fullest 🙂

@987Nabil I'm working on this feature, caught up with some issues will be pushing for PR review by next week 😄

2022-08-23 07:24 UTC, AndrewBastin commented on packages/hoppscotch-app/helpers/RequestRunner.ts
> +              console.log("TEAM-VAR-UPDATED")
No logs :)

2022-08-23 10:07 UTC, AndrewBastin requested changes
look into the given corrections

2022-08-23 10:07 UTC, AndrewBastin commented on packages/hoppscotch-app/components/environments/teams/Details.vue
> +const saveEnvironment = () => {
Save Environment Modal should wait until the actual saving to be done before the modal is closed along with a loading state.
It isn't currently.

2022-08-29 12:29 UTC, nivedin commented on packages/hoppscotch-app/helpers/editor/extensions/HoppEnvironment.ts
> +  "bg-red-500 text-primary hover:bg-red-600"
I have replaced this styling with an my and team env icon on the tooltip.

2022-09-29 03:41 UTC, nickwph commented
hello! we have been waiting for this feature, hope this can be merged soon!

2022-10-07 09:51 UTC, AndrewBastin requested changes
`helpers/backend/gql/mutations/DeleteAllVariablesFromTeamEnvironment.graphql` is empty.

Please look into the given issues.

2022-10-07 09:51 UTC, AndrewBastin commented on packages/hoppscotch-app/src/helpers/teams/TeamEnvironmentAdapter.ts
> +  private updateTeamEnvironment(updatedEnvironment: TeamEnvironment) {
Team Environment renames do not trigger updates.

Steps to repro:
1. Use Hoppscotch with 2 users (single user also has issue, but this should work too)
2. Point both of them to the same team and use Team Environments.
3. Create a Team Environment.
4. Then, rename the team environment.
5. Observe that the environment has not been renamed.

I haven't checked if its just the name or other parts too, please do check.

2022-10-07 16:32 UTC, AndrewBastin approved these changes
lgtm :100:

Although we should definitely also think about adding ability to import an environment from personal.

2022-10-07 16:35 UTC, merged