feat: added possibility to order requests alphabetically (#2261)
hoppscotch/hoppscotch pull request #2755
Opened 2022-10-09 13:07 UTC by AbderrahmaneGuermat

Closes #2261 

### Description

I added a button which allows users to sort the requests alphabetically. To implement this feature I added a flag which controls the sorting process of the requests

### Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [X] All the tests have passed

**Current preview of the feature**

https://user-images.githubusercontent.com/61157096/194758255-03126f84-fffc-422b-8bd4-90664a8008da.mp4

2022-10-11 08:58 UTC, AndrewBastin requested changes
The feature is not working.

Clicking on the sort button doesn't do anything in My Collections section from my usage.

2022-10-11 08:58 UTC, AndrewBastin commented on packages/hoppscotch-app/src/components/collections/index.vue
> +    ChangeFlagOrder() {
Function names should be `camelCase`

2022-10-11 08:58 UTC, AndrewBastin commented on packages/hoppscotch-app/src/components/collections/index.vue
> +            :title="Order"
There should be an `i18n` tag here.
Also this bound variable doesn't exist.
`:prop`'s assigned value is not considered as a string, but as a JS expression.

React equivalent
```
<ButtonSecondary title={{ Order }} />
```

2022-10-11 10:00 UTC, liyasthomas commented
Save context doesn't respect sorted order.

Steps to reproduce:
1. Select a request from any Collection
2. Apply sort on the collections
3. See the select/save context doesn't respect sorted order instead it sticks to the previous order which breaks the feature.

cc: @AndrewBastin

2022-10-22 07:11 UTC, AndrewBastin commented
As there is no response from the OP in the past 10 days, this PR will now be closed because of inactivity.

We can reopen if you are interested in pursuing the PR.

2022-10-22 07:11 UTC, closed without merging