refactor: move global env to top in UI
hoppscotch/hoppscotch pull request #2848
Opened 2022-11-02 19:24 UTC by nivedin

### Description
This PR moves the global environment above the environment type selection toggle so that it's visible in both my and team's environment state. It also fixes an issue where the environment state does not revert back to my environment when the user logs out.

**Before**

![image](https://user-images.githubusercontent.com/53208152/199581455-a93097b7-378e-4709-957f-642bf5688da4.png)

**After**

![image](https://user-images.githubusercontent.com/53208152/199581374-56182c9f-c663-45fa-92d1-7fc907cf1c0f.png)

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2022-11-02 21:01 UTC, AndrewBastin requested changes
Just this minor issue.

Good PR opening comment!

2022-11-03 04:21 UTC, liyasthomas reviewed
Excellent PR description 👏👏

2022-11-03 04:34 UTC, liyasthomas approved these changes
LGTM 💯

2022-11-03 04:41 UTC, liyasthomas commented on packages/hoppscotch-app/src/components/environments/my/index.vue
> +    envName !== "Global" && editEnvironment(envIndex)
Resolved

2022-11-03 04:43 UTC, merged