refactor: tighten the types for REST response components
hoppscotch/hoppscotch pull request #2917
Opened 2023-02-03 15:17 UTC by aitchnyu

Intended to be follow up of https://github.com/hoppscotch/hoppscotch/pull/2915

### Description

ResponseBodyRenderer had response props of `{ type: Object, default: () => ({}) }`. Updated to `{ type: Object as PropType<HoppRESTResponse> | null }` instead. 

Which uncovered that `headers` prop in `HeadersRendererEntry.vue` and `header` prop in `HeadersRenderer.vue` were wrongly given as `HoppRESTHeader` (it has key, value, active properties). Updated those to the `HoppRESTResponseHeaderKV` type.

In `ResponseMeta.vue` response prop was updated to `HoppRESTResponse | null`. Updated the code so tsc finds the null checks ok.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information

2023-02-06 06:42 UTC, AndrewBastin requested changes

2023-02-06 09:16 UTC, aitchnyu commented on packages/hoppscotch-common/src/components/lenses/ResponseBodyRenderer.vue
> +    const allRenderers = [
Renamed https://github.com/hoppscotch/hoppscotch/pull/2917/commits/12a63d8e85f38facb252ab90d3e276b88706ddc5#diff-7bd0dd7a585134a2dd8d53d7ebd4afd50a6b81f6ab5ae4d24cf3f2ece20444f8R93

2023-02-06 09:17 UTC, aitchnyu commented on packages/hoppscotch-common/src/components/lenses/ResponseBodyRenderer.vue
> +      getLocalConfig("response_selected_lens_tab") ?? ""
Removed blank string https://github.com/hoppscotch/hoppscotch/pull/2917/commits/12a63d8e85f38facb252ab90d3e276b88706ddc5#diff-7bd0dd7a585134a2dd8d53d7ebd4afd50a6b81f6ab5ae4d24cf3f2ece20444f8R98

2023-02-08 04:57 UTC, AndrewBastin approved these changes
lgtm 💯

2023-02-08 04:59 UTC, merged