feat: rest revamp
hoppscotch/hoppscotch pull request #2918
Opened 2023-02-04 13:59 UTC by anwarulislam

### Description
This PR introduces a new Tab feature for our Hoppscotch.io REST Platform. This Tab System has been long requested by our users and will greatly enhance their experience.

Before this feature, our platform lacked the ability to easily switch between different requests within a single view. With this new tab system, users can now navigate between multiple requests with ease, leading to a more organized and streamlined experience.

We are storing all tabs inside `RESTSession.ts` store. and each tab having request property with `RESTRequest.ts` class containing request for that tab.

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2023-03-09 11:08 UTC, nivedin requested changes

2023-03-14 16:47 UTC, AndrewBastin requested changes
please do look into the given issues.

2023-03-14 16:47 UTC, AndrewBastin commented on packages/hoppscotch-common/src/components/http/RequestTab.vue
> +const tab = ref(cloneDeep(props.modelValue))
Why the `cloneDeep` ?

2023-03-20 11:32 UTC, nivedin requested changes
@anwarulislam please look into these comments

2023-03-27 16:53 UTC, AndrewBastin requested changes
only the current given issues. rest all looks good

2023-03-27 16:53 UTC, AndrewBastin commented on packages/hoppscotch-common/src/pages/index.vue
> +      console.log("TABSTATE FROM SYNC", tabStateFromSync)
remove the console.log

2023-03-28 10:00 UTC, nivedin requested changes
@anwarulislam please look into these issues.

2023-03-30 18:25 UTC, nivedin requested changes
only found this issue.. rest looks all good

2023-03-30 18:25 UTC, nivedin commented on packages/hoppscotch-common/src/components/collections/index.vue
when deleting a team request which is opened as an active tab throws this error

![image](https://user-images.githubusercontent.com/53208152/228929327-a369fc49-9e21-479d-8b19-e51ec92c064e.png)

2023-03-30 19:08 UTC, AndrewBastin approved these changes
lgtm 💯

2023-03-30 19:15 UTC, merged