chore: use auto-imported icons
hoppscotch/hoppscotch pull request #2998
Opened 2023-04-17 17:37 UTC by liyasthomas

### Description
We're using [unplugin-icons](https://github.com/antfu/unplugin-icons) to load icons as components on-demand.
This PR changes all instances of manual icon imports to leverage unplugin-icons' [auto Importing](https://github.com/antfu/unplugin-icons#auto-importing) feature.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2023-04-18 11:51 UTC, JoelJacobStephen approved these changes
LGTM!!

2023-04-19 09:32 UTC, nivedin requested changes
please change [this](https://github.com/hoppscotch/hoppscotch/blob/bd09a6ac452940cfd178c7f3146d6ce82fb41014/packages/hoppscotch-common/src/components/http/TestResult.vue#L45) icon to use auto-imported icon.

`<icon-lucide-alert-triangle class="mr-4 svg-icons" />`

2023-04-19 09:38 UTC, liyasthomas commented
Ty for finding that missed icon, I've fixed it in https://github.com/hoppscotch/hoppscotch/pull/2998/commits/621334e1367bfe30fdce390a382c433480ab4d81

2023-04-19 09:43 UTC, nivedin approved these changes
LGTM 💯

2023-04-21 14:50 UTC, merged