Fix/locale en url issue
hoppscotch/hoppscotch pull request #3006
Opened 2023-04-19 10:57 UTC by anwarulislam

Closes #2959 

### Description
This PR resolves the issue of switching to `en` locale from URL slug. Allowed dynamic import using `vite-plugin-vue-i18n` this plugin.

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2023-04-20 10:22 UTC, amk-dev requested changes

2023-04-20 10:22 UTC, amk-dev commented on packages/hoppscotch-common/src/modules/i18n.ts
>        allowComposition: true,
can you also remove this unused import 

`import en from "../../locales/en.json"`

2023-04-21 16:56 UTC, anwarulislam commented
It is also working after adding a little delay before switching to `en` inside onBeforeRouteChange

2023-04-21 21:00 UTC, amk-dev submitted a review, later dismissed
LGTM 🚀

2023-04-22 10:52 UTC, merged