Fix: tab system breaks when a new tab is created while waiting for response in another tab
hoppscotch/hoppscotch pull request #3031
Opened 2023-05-03 21:55 UTC by anwarulislam

### Issue
The current tab system breaks when a user creates a new tab while waiting for a response in another tab. This issue causes unexpected behavior and impacts user experience.

### Description
This pull request fixes the issue by implementing a check for pending requests `onBeforeUnmount` in the active tab. If a pending request is found, cancel the request.

- [ ] Not Completed
- [x] Completed

2023-05-08 16:25 UTC, nivedin approved these changes
LGTM 💯

2023-05-08 17:53 UTC, AndrewBastin commented
@liyasthomas can you also just verify the fix ?

2023-05-08 18:21 UTC, AndrewBastin requested changes

2023-05-09 05:11 UTC, liyasthomas approved these changes
LGTM 💯

2023-05-10 13:45 UTC, AndrewBastin approved these changes

2023-05-10 13:46 UTC, merged