feat: introducing a new input hoppscotch ui component
hoppscotch/hoppscotch pull request #3089
Opened 2023-05-29 12:49 UTC by JoelJacobStephen

### Description
Introduces a new Input UI component in `hoppscotch-ui` where the input box implementation is abstracted into the new ui component.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2023-07-03 02:44 UTC, anwarulislam requested changes
@JoelJacobStephen please look at these two comments.

2023-07-03 02:44 UTC, anwarulislam commented on packages/hoppscotch-ui/src/components/smart/Input.vue
> +    inputStyles: any
The type shouldn't be `any`

2023-07-03 02:44 UTC, anwarulislam commented on packages/hoppscotch-ui/src/components/smart/Input.vue
> +    inputType: string | (string | false)[]
Why is this `inputType` prop for? I can't see any usage in the component.

2023-07-17 07:45 UTC, anwarulislam approved these changes
LGTM 🚀

2023-08-01 13:58 UTC, nivedin requested changes
please look into these comments

2023-08-01 13:58 UTC, nivedin commented on packages/hoppscotch-sh-admin/src/components/users/InviteModal.vue
> +        label="Email Address"
```suggestion
        :label="t('users.email_address')"
```

2023-08-01 13:58 UTC, nivedin commented on packages/hoppscotch-common/src/pages/profile.vue
> +  console.log(displayName.value)
remove console statement

2023-08-05 18:15 UTC, merged