fix: use --location param for url when parsing curl
hoppscotch/hoppscotch pull request #3152
Opened 2023-06-19 12:51 UTC by amk-dev

**Before**

We were not respecting the `--location` parameter when parsing the curl request.

**After** 

Respect the `--location` parameter when parsing the curl request.

2023-06-19 14:13 UTC, nivedin requested changes
```
curl --location 'http://my-private-url.test.com/'
--header 'Accept: application/jsonx'
--header 'Content-Type: application/jsonx'
--data '{"a":1,"b":2,"c":3}'
```

when trying to import the curl the body is not set, and setting the header has also some bugs.

2023-06-20 13:12 UTC, nivedin approved these changes
LGTM 💯

2023-06-20 18:04 UTC, AndrewBastin requested changes

2023-06-20 18:04 UTC, AndrewBastin commented on packages/hoppscotch-common/src/components/http/RequestOptions.vue
> +watch(props, (updatedProps) => {
I think we have `request` just representing the modelValue right ?
In that case, why not just define `request` using `useVModel` ?

Will something break ?
```ts
import { useVModel } from "@vueuse/core"

const request = useVModel(props, "modelValue", emit)
```

2023-06-22 18:09 UTC, AndrewBastin approved these changes
lgtm

2023-06-22 18:10 UTC, merged