[feat] : Allow admins to revoke a team invite (HBE-230)
hoppscotch/hoppscotch pull request #3162
Opened 2023-06-27 09:15 UTC by ankitsridhar16

Closes # HBE-230

### Description
Currently Admins can view pending invitations for a team, but they can't revoke an invitation. This PR introduces a mutation to revoke a team invite by invite ID that will be used from the admin dashboard.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Additional Information

Testing Instructions:
- Create a team and invite users by email
- get pending invitations for the team by team ID
- use `revokeTeamInviteByAdmin` mutation with a invite ID

2023-07-07 06:42 UTC, mirarifhasan requested changes

2023-07-07 06:42 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/admin/admin.service.ts
> +    if (E.isLeft(teamInvite)) return E.left(TEAM_INVITE_NO_INVITE_FOUND);
```suggestion
    if (E.isLeft(teamInvite)) return E.left(teamInvite.left);
```

2023-07-14 09:34 UTC, balub commented on packages/hoppscotch-backend/src/admin/admin.service.ts
> +    if (E.isLeft(teamInvite)) return E.left(TEAM_INVITE_NO_INVITE_FOUND);
+1

2023-07-14 09:35 UTC, balub requested changes
The team-invitation methods used have been modified after the team-invitations refractor, please update to reflect changes.

2023-07-25 11:44 UTC, mirarifhasan approved these changes
LGTM

2023-07-28 01:00 UTC, mirarifhasan approved these changes

2023-08-03 08:33 UTC, balub approved these changes
LGTM 🚀 .

2023-08-03 08:38 UTC, merged