feat: context menu
hoppscotch/hoppscotch pull request #3180
Opened 2023-07-11 11:27 UTC by nivedin

Closes HP-15

### Description
This PR adds the context menu feature where a user can select any text which popups up a menu where the user will be provided with options respectively where the text is selected.

selection done in codemirror input field and response section 
- environments setting
- parameters altering in the URL input 
- links opening (new hopp tab or new browser tab)

### Checks
- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2023-07-14 05:21 UTC, liyasthomas commented
1. Often, the complete selected text is not populated to the "set as an environment" modal. This happens at every time, but sometimes unexpectedly.

[bac4578e-68cf-4586-ad9d-ba44a6946c6a.webm](https://github.com/hoppscotch/hoppscotch/assets/10395817/74e5cab7-4fa0-4664-b64b-dab5a9331a66)

---

2. Set "Global" as default when no environment is selected. Set the current environment as default when an environment is selected.

[90403cd2-601b-4b6f-a4dc-f3885a48dc0c.webm](https://github.com/hoppscotch/hoppscotch/assets/10395817/27086634-fd65-4979-b027-3d36bbfebebd)

---

3. Often, "open in new tab" is not visible. This could be due to issue # 1. (selected text is not populated). A bit tricky to reproduce as well.

[a49203ec-069d-43d1-a8b1-3a86486d1b9c.webm](https://github.com/hoppscotch/hoppscotch/assets/10395817/768f4ce9-45cc-4a83-985d-67967c5da99c)

2023-07-14 05:22 UTC, liyasthomas requested changes
https://github.com/hoppscotch/hoppscotch/pull/3180#issuecomment-1635290135

2023-07-14 15:06 UTC, liyasthomas approved these changes
LGTM 💯

2023-07-18 11:30 UTC, anwarulislam approved these changes
LGTM 🚀

2023-07-18 11:30 UTC, anwarulislam commented on packages/hoppscotch-common/src/components/app/ContextMenu.vue
> +// })
Do we need this?

2023-07-18 13:24 UTC, liyasthomas commented on packages/hoppscotch-common/src/components/app/ContextMenu.vue
> +// })
We can clean up this later.

2023-07-27 18:14 UTC, liyasthomas commented
`onClickOutside` doesn't seem to be working for me. Clicking outside the context menu doesn't close the active content menu instance.

2023-07-28 04:09 UTC, liyasthomas approved these changes
LGTM 💯

2023-07-31 06:03 UTC, anwarulislam approved these changes
LGTM 🚀

2023-08-01 08:10 UTC, AndrewBastin requested changes

2023-08-01 08:10 UTC, AndrewBastin commented on packages/hoppscotch-common/src/services/context-menu/index.ts
> +  getMenuFor: (text: string) => ContextMenuState
I think a doc comment for what this function does will be useful.

2023-08-01 08:10 UTC, AndrewBastin commented on packages/hoppscotch-common/src/services/context-menu/index.ts
> +export interface ContextMenu {
This should be a `type` rather than an `interface` right ?

```suggestion
export type ContextMenu = {
```

2023-08-02 05:49 UTC, liyasthomas approved these changes
LGTM 💯

2023-08-02 15:19 UTC, AndrewBastin approved these changes

2023-08-02 15:22 UTC, merged