fix: firefox browser scrollbar issue
hoppscotch/hoppscotch pull request #3201
Opened 2023-07-20 09:38 UTC by anwarulislam

Closes HFE-74

### Description

This PR fixes the issue of showing the default `scrollbar-thumb` instead of the custom one on Firefox for HoppUI Windows Scrollbar.

2023-07-20 10:11 UTC, liyasthomas commented on packages/hoppscotch-ui/src/components/smart/Windows.vue
> +
can we achieve the same with tailwindcss class `overflow-hidden` inline HTML?

2023-07-20 10:13 UTC, liyasthomas commented on packages/hoppscotch-ui/src/components/smart/Windows.vue
> +    @apply active:bg-secondaryLight;
Better to use `focus-visible` instead of `active` state.

2023-07-20 10:13 UTC, liyasthomas commented on packages/hoppscotch-ui/src/components/smart/Windows.vue
> +    @apply active:bg-secondaryLight;
Better to use `focus-visible` instead of `active` state.

2023-07-20 10:14 UTC, liyasthomas requested changes
check the comments.

2023-07-26 07:13 UTC, nivedin requested changes

2023-07-26 07:13 UTC, nivedin commented on packages/hoppscotch-ui/src/components/smart/Windows.vue
> +        class="flex flex-1 flex-shrink-0 w-0 scroll-container overflow-hidden"
we can remove the unused `scroll-container` class.

2023-07-26 07:13 UTC, nivedin commented on packages/hoppscotch-ui/src/components/smart/Windows.vue
> +    class="flex flex-col flex-1 h-auto overflow-y-hidden flex-nowrap hopp-windows"
we can remove the unused `hopp-windows` class.

2023-07-27 18:04 UTC, liyasthomas approved these changes
LGTM 💯

2023-07-28 16:51 UTC, nivedin approved these changes
LGTM 💯

2023-08-01 07:50 UTC, merged