feat: inspections
hoppscotch/hoppscotch pull request #3213
Opened 2023-07-26 06:40 UTC by nivedin

Closes HP-32

### Description
This feature adds the inspection ability to hoppscotch. Users on Hoppscotch could run into possible errors while using the App. The inspections feature or the inspector helps the user understand what all possible errors could be present while:

1. Configuring the app
2. Configuring the request
3. Configuring headers
4. Sending requests
5. Environment not activated

This will help users to debug issues easily and simplify their workflow.

### Checks
- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### TODOS
- [ ] Add features to the response inspector
- [ ] Single point of inspection results besides URL input
- [ ] Write tests

2023-08-07 16:29 UTC, liyasthomas requested changes
Inspections are triggered when the response is loading. This case shouldn't happen.

[c14d5ce1-dabe-458d-b80f-83d55b42c95c.webm](https://github.com/hoppscotch/hoppscotch/assets/10395817/64fa3771-9f49-418d-8257-80f0c42a4816)

<img width="1470" alt="Screenshot 2023-08-07 at 9 32 12 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/7b9ab080-752a-4116-bc5c-0986dd4b7ef5">

2023-08-07 16:29 UTC, liyasthomas commented on packages/hoppscotch-common/src/components/http/ResponseMeta.vue
> +          : 'mr-2',
Can you share a screenshot of these cases?
1. `'absolute right-0 top-0'`
2. `'mr-2'`

I think it'd be better if we put the alert icon on the right-hand side. So you might want to change 2. to `'ml-2'` as a safe margin between the Inspections component and Response's meta.

2023-08-11 03:15 UTC, liyasthomas approved these changes
LGTM 💯

2023-08-17 20:07 UTC, AndrewBastin approved these changes

2023-08-17 20:07 UTC, merged