feat: tippy menu for history and tab
hoppscotch/hoppscotch pull request #3220
Opened 2023-07-28 16:28 UTC by nivedin

Closes HFE-132

### Description
- Adds a right-click tippy to the history item which allows the user to save the history request to a collection
  
![image](https://github.com/hoppscotch/hoppscotch/assets/53208152/6ca589ae-7b10-4e58-a892-e18246dbf43a)

- Adds a right-click tippy to the tab which allows the user to 

   - rename a tab
   - duplicate  tab
   - close the tab
   - close all other tabs
   
   
![image](https://github.com/hoppscotch/hoppscotch/assets/53208152/475f649f-a559-4587-9125-d3fcea24d6ce)

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### TODO
- [ ] fix the bug when closing all other tabs except the clicking one

2023-07-29 11:48 UTC, liyasthomas requested changes
<img width="1470" alt="Screenshot 2023-07-29 at 5 07 58 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/aa3c5554-baf6-422e-8ae8-80bc7060812a">

1. "Close Tab" should be disabled when there's only one tab.
2. "Close other Tabs" should be disabled when there's only one tab.

2023-07-31 06:20 UTC, liyasthomas approved these changes
LGTM 💯

2023-07-31 06:46 UTC, anwarulislam approved these changes
LGTM 🚀

2023-08-01 07:30 UTC, AndrewBastin requested changes

2023-08-01 07:30 UTC, AndrewBastin commented on packages/hoppscotch-common/src/components/http/Request.vue
> +const request = ref<HoppRESTRequest | HoppGQLRequest | null>(null)
Try not to introduce `HoppGQLRequest` stuff into the Http components.

2023-08-01 07:30 UTC, AndrewBastin commented on packages/hoppscotch-common/src/components/http/Request.vue
> +  }
Since, `request` can be a `HoppGQLRequest`, make sure that situation is validated.

2023-08-01 07:30 UTC, AndrewBastin commented on packages/hoppscotch-common/src/helpers/actions.ts
> +  }
I would suggest the unions be discriminated based on a `requestType` field to make it easier to validate. Either that or you should split this event for `rest.request.save-as` and `gql.request.save-as`.

```suggestion
  "request.save-as":
  	| {
    		requestType: "rest"
    		request: HoppRESTRequest
  	  }
  	| {
  		requestType: "gql"
  		request: HoppGQLRequest
  	  } 
```

2023-08-01 07:30 UTC, AndrewBastin commented on packages/hoppscotch-common/src/helpers/rest/tab.ts
> +    console.warn(`Tried to close a tab which does not exist (tab id: ${tabID})`)
Correct the warning message.

2023-08-01 07:30 UTC, AndrewBastin commented on packages/hoppscotch-common/src/helpers/rest/tab.ts
> +  }
This won't happen right ?

2023-08-01 07:30 UTC, AndrewBastin commented on packages/hoppscotch-common/src/pages/index.vue
> +const onResolveConfirmSCloseAllTabs = () => {
Typo on function name ?

2023-08-08 07:50 UTC, AndrewBastin approved these changes
lgtm 💯

2023-08-08 07:53 UTC, merged