feat: introduces ability to export single environment variables and also allow CLI to accept the export format used by the app
hoppscotch/hoppscotch pull request #3380
Opened 2023-09-21 10:03 UTC by JoelJacobStephen

### Ticket
Closes HFE-203

### Description
This PR introduces the following features and fixes to the `Hoppscotch App` and `Hoppscotch CLI`

**Features Added:**
- Added the ability to export single environment variables from the `Hoppscotch App` in both REST and GraphQL Sections.
- CLI can now accept environment variables from the format in which the `Hoppscotch App` exports.
- Introduced `Zod` package into the `Hoppscotch CLI` to check the validity of the formats for the Environment variables.

**Issues Fixes:**
- Fix the malformed environments error when importing a environment file that was exported from the `Hoppscotch App` to the CLI.   

### Objectives
- [x] Add ability to export single environment variables from REST and GraphQL
- [x] On export of environment variables, remove id from environment and send only the name and variables.
- [x] The CLI should be able to receive the format that is exported when exporting environment variables from the Hoppscotch App.
- [x] Fix the malformed environments error when importing a environment file that was exported from the app to the CLI.     

### Note

> Requires changes to the Documentation as the CLI can now accept the format that the `Hoppscotch App` uses to export environment variables

### Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2023-09-28 17:03 UTC, AndrewBastin approved these changes

2023-10-01 07:49 UTC, jamesgeorge007 commented on packages/hoppscotch-cli/package.json
> +    "zod": "^3.22.2"
Shouldn't we add this under `devDependencies` similar to other packages such that it gets inlined?

2023-10-03 06:30 UTC, nivedin requested changes
Exporting of only personal environments is done we need to implement the same for team environment as well

2023-10-03 17:02 UTC, jamesgeorge007 reviewed
Can you verify if the CLI accepts the environment exported as a whole? It was throwing when I gave it a shot.

2023-10-03 17:02 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/components/environments/my/Environment.vue
> +  a.download = `${url.split("/").pop()!.split("#")[0].split("?")[0]}.json`
Could you elaborate on what's happening here? A comment will be useful as well. Also, can it be simplified?

2023-10-03 17:02 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/components/environments/teams/Environment.vue
It seems like we're repeating the logic here. Can we possibly abstract out the common elements?

2023-10-04 17:02 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/helpers/import-export/export/envToJson.ts
> +export const exportJSON = (
I'd prefer naming it `exportToJson` / `exportAsJson`. Feel free to ignore it if you feel unnecessary.

2023-10-05 04:15 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/helpers/import-export/export/envToJson.ts
> +}
We also need to check the case where environmentIndex can be 0 and the fallback isn't intentional.

2023-10-05 08:45 UTC, jamesgeorge007 reviewed
Looks good, left a few minor comments. As discussed, let's add tests for the changes. Also, please ensure to raise a PR for the docs updates required.

2023-10-05 08:45 UTC, jamesgeorge007 commented on packages/hoppscotch-cli/src/types/request.ts
> +  })
```suggestion
  HoppEnvExportObject
```

We can reuse the above definition, right?

2023-10-05 08:45 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/components/environments/my/Environment.vue
> +const exportAsJson = ref<typeof HoppSmartItem>()
Maybe let's append `el` => `exportAsJsonEl` to the name above so that it stands out from the utility function that gets imported.

2023-10-05 08:45 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/components/environments/teams/Environment.vue
> +const exportAsJson = ref<typeof HoppSmartItem>()
Maybe let's append `el` => `exportAsJsonEl` to the name above so that it stands out from the utility function that gets imported.

2023-10-06 05:51 UTC, merged