fix: mailer template issue
hoppscotch/hoppscotch pull request #3475
Opened 2023-10-25 09:03 UTC by balub

Closes HBE-304

### Description

In this PR, we fix a known issue with the mailer module where the `templates` folder is not present in the `dist` folder after the image has been built.

### Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### Testing info
Make sure to build the image using the following command, with the necessary changes.
```
docker build -t hoppscotch-local-aio -f prod.Dockerfile --target aio .
```
 Check if the following type of emails are being sent correctly using `mailcatcher`:
- User-Invitations from the admin app.
- Team-Invitation for the app.

2023-10-31 10:12 UTC, mirarifhasan approved these changes
Works for me

2023-11-01 05:15 UTC, AndrewBastin requested changes

2023-11-01 05:15 UTC, AndrewBastin commented on packages/hoppscotch-backend/src/templates/code-your-own.hbs
can this file be named to something else, as the name doesn't reflect what the file template contains ?

2023-11-01 06:22 UTC, balub commented on packages/hoppscotch-backend/src/templates/code-your-own.hbs
Sure

2023-11-06 11:42 UTC, AndrewBastin approved these changes
lgtm :100:

2023-11-06 11:55 UTC, merged