added getTracker to all Guards
hoppscotch/hoppscotch pull request #3535
Opened 2023-11-10 13:31 UTC by RaHehl

(maybe) Closes # 3381

### Description
For bug #3381, the cause appears to be @nestjs/throttler, at least according to the report of an internal user who saw something with "throttling" in the log when the team environments disappeared. I suspect this is because the Hoppscotch API runs in Kubernetes and therefore there is an ingress proxy running between the API and the client. I don't know anything about NestJS, I think the solution to this lies in the direction of this PR.

2024-01-12 06:29 UTC, balub commented
@RaHehl I believe adding the `getTracker` function only in the `gql-throttler.guard.ts` file is enough, so can you remove it from the auth-guard.

2024-01-12 06:30 UTC, balub requested changes
@RaHehl I believe adding the getTracker function only in the gql-throttler.guard.ts file is enough, so can you remove it from the auth-guard.

2024-01-12 06:53 UTC, RaHehl commented
> @RaHehl I believe adding the getTracker function only in the gql-throttler.guard.ts file is enough, so can you remove it from the auth-guard.

done

2024-01-31 08:41 UTC, balub approved these changes

2025-04-29 08:44 UTC, mirarifhasan approved these changes
LGTM

2025-04-29 08:59 UTC, merged