HBE-326 feature: server configuration through GraphQL API
hoppscotch/hoppscotch pull request #3591
Opened 2023-11-24 09:09 UTC by mirarifhasan

Closes # 

### Description

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### Additional Information

2023-11-27 06:38 UTC, balub requested changes

2023-11-27 06:38 UTC, balub commented on packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
> +      },
Remove SAML related details from this PR.

2023-11-27 06:48 UTC, balub commented
@mirarifhasan can you convert this PR to a draft one.

2023-12-08 10:10 UTC, balub requested changes

2023-12-08 10:56 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/admin/infra.resolver.ts
> +  }
@balub In Admin Dashboard, frontend calls this query `allowedAuthProviders`

https://hoppscotchworkspace.slack.com/archives/C04C148N2JK/p1702014906806529?thread_ts=1701954362.399499&cid=C04C148N2JK

2023-12-08 11:04 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
> +          })),
You're right @balub.
I'll change it

2023-12-08 11:10 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
> +      return E.right(this.cast(infraConfig));
I think we can leave it. `update()` method is a helper function for other methods like `enableAndDisableSSO()`.
IMO, good to return from this helper function.

2023-12-08 11:27 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
> +    return E.right(true);
changed a bit

2023-12-11 09:14 UTC, balub requested changes

2023-12-11 09:14 UTC, balub commented on packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
> +  validateEnvValues(
I think we can add a check for the `MAILER_ADDRESS_FROM` variable here too.

2023-12-11 09:16 UTC, balub commented on packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
> +  validateEnvValues(
How about `VITE_ALLOWED_AUTH_PROVIDERS` too?

2023-12-11 11:03 UTC, balub requested changes

2023-12-11 11:03 UTC, balub commented on packages/hoppscotch-backend/src/infra-config/infra-config.service.ts
> +      }
We should use a `switch` here.

2023-12-11 12:31 UTC, balub approved these changes

2023-12-11 13:26 UTC, balub approved these changes

2023-12-12 07:23 UTC, balub approved these changes

2023-12-12 10:29 UTC, ankitsridhar16 approved these changes

2023-12-12 10:30 UTC, ankitsridhar16 approved these changes

2023-12-12 10:42 UTC, merged