Collection Runner Feature
hoppscotch/hoppscotch pull request #3600
Opened 2023-11-28 11:58 UTC by anwarulislam

Closes HFE-236

### Description

This PR introduces the Collection Runner feature.

- [x] Not Completed
- [ ] Completed

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2023-12-26 08:55 UTC, tomerr-ma commented
Any chance this PR will be merged soon?

2024-02-14 11:26 UTC, LewisBango commented
@anwarulislam hi, is there any update on this one please?

2024-02-19 05:16 UTC, guysha20 commented
Hi @anwarulislam, any time estimation for merging this one?

2024-02-23 20:15 UTC, MarcelHoell commented
Hi, this is gonna be a very nice feature! When to you plan to release it?

2024-02-28 07:41 UTC, amishratnasthapit commented
Looking forward to this feature.

2024-03-12 17:53 UTC, christopher-nash commented
I noticed the docs have a page which mentions the runner: https://docs.hoppscotch.io/documentation/features/runner but apparently those documents were updated prematurely?

The lack of a runner is the one feature thats holding me back from entirely jumping ship from Postman so I'm really eager for this feature.

2024-03-18 19:33 UTC, marcelocastilho reviewed
:eyes:

2024-03-24 13:03 UTC, Zamion101 commented
This feature is a really wanted feature for to be able to test REST APIs quickly and autonomously. Last update/commit in this PR dates to 3 months ago and no further update mentioned or PR closed. If its possible we would like to get some update on this PR and ETA of this update to main branch. Thanks.

2024-04-01 04:42 UTC, thetronjohnson commented
Hi, quick update on the collection runner: we're waiting for a refactor to be finished for the collection runner to work at its best. We're focusing on completing the refactor this month and getting this feature merged.

2024-04-02 08:33 UTC, LewisBango commented
@thetronjohnson Thanks, that's great to hear.

One question, will the runner support running individual folders as well as the entire collection?

2024-04-26 02:42 UTC, RJRReid commented
I work for a large company that very soon will need to replace POSTMAN.
However, whatever it gets replaced with will have to have a Runner that uses a CSV as input.
If you can get this working, I might convince my company to purchase several hundred of the licenses for the paid version.

2024-06-14 01:59 UTC, WanwanNoOne commented
@anwarulislam hi, is there any update on this one please?

2024-06-14 02:00 UTC, WanwanNoOne commented
@hoppscotch hi, is there any update on this one please?

2024-08-28 18:51 UTC, NeilRiver commented
apparently never

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣴⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣦⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠿⠿⣿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠛⠋⢻⣇⠀⠀⠸⣇⠀⠀⢰⡏⠀⣸⠇⠀⢀⡿⠀⢹⡏⢹⡟⠻⣿⣿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⣯⡁⠹⣧⣀⣤⣿⣦⢴⣶⣿⣶⣶⣿⠥⠤⠿⠦⠤⢼⣧⣀⣿⣀⣼⠃⢰⡏⠈⣿⢿⡆⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠉⢷⡄⠘⣷⣶⠿⠽⠒⠚⠉⠉⠀⠀⠀⠀⠉⠙⠒⠒⠒⠒⠒⠒⠒⢼⠉⠙⠓⢿⣄⣰⡿⢸⣷⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡛⠉⠻⣆⣀⣿⠟⠉⠀⠀⠀⠀⣀⣀⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣀⡀⠀⠀⠈⠻⢷⡾⣿⡇⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⡿⣯⡈⠻⢶⣤⠾⠋⠁⠀⠀⠴⠚⠉⠉⠁⠀⠀⠀⠀⢩⡀⠀⠀⠀⠀⠀⠀⠐⡋⠀⠀⠀⠉⠳⣄⠀⠀⠘⣷⣿⡇⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⠻⣦⡈⢻⣴⠟⠁⠀⠀⠀⠀⠀⠀⣤⠤⠤⠴⠖⠀⠀⠀⠀⠹⡆⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⣀⣀⠀⠀⠀⠀⣿⣾⠁⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⡋⠙⢦⣌⣻⡿⠁⠀⠀⠀⠀⠀⠀⡀⠀⠀⠀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠀⠀⠀⠀⠈⠉⠓⠦⠄⣸⠇⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠉⠻⣦⡀⢹⡟⠀⠀⣀⠀⠀⠀⠀⠼⠿⠗⠸⣯⡉⣿⣿⣿⣿⠟⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⠶⢶⣤⣤⣤⠀⢀⡐⣿⠀⠀⠀⠀⠀⠀⠀⡀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⠙⣧⡀⠉⣻⡟⠁⠀⠀⢱⣧⣤⠀⠀⠀⠀⠀⢰⠾⠿⡿⠿⠿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠰⣟⢶⣾⣿⣿⣿⠀⠻⣤⣿⡀⠀⠀⠀⠀⠀⢰⠃⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣆⠈⠻⣦⡟⠀⠀⠀⠀⢘⣷⢿⠄⠀⠀⠀⠀⠘⠓⠲⠿⣿⣿⣷⡿⠃⠀⠀⠀⠀⠀⠀⠀⣷⠀⠙⠿⣷⣾⣿⣏⣤⠀⠀⢸⣷⠀⠀⠀⠀⠀⣸⠁⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣆⠀⢸⡇⠀⠀⠀⠀⢰⣿⣬⡳⣃⡄⠀⠀⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣆⠀⠀⠙⠃⠀⠀⠀⠀⠀⠚⣿⠀⠀⠀⠀⣠⣾⠏⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢷⣼⠇⠀⠀⠀⠀⢸⡇⢬⠱⢸⣘⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣦⡀⠀⠀⠀⢀⡈⢀⠰⣝⣿⠀⠀⢰⣳⠋⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣙⣧⠀⠀⠀⠀⠸⣷⣃⢯⡤⡿⣅⠀⢦⡀⠀⠀⠀⠀⠀⠀⣠⡤⠶⠀⠀⠀⠀⠀⠀⠀⠈⣿⠀⠀⠀⠀⠑⢿⡟⣺⠏⠀⠀⣧⠃⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⢿⡇⠀⠀⠀⠀⢹⣗⡃⠹⢄⠙⣆⠤⠘⠀⠀⠀⠀⢠⡀⢻⣆⠀⠀⢀⣀⡀⠀⠀⠀⣾⠃⠀⠀⠰⢠⢚⣿⣿⡟⠀⠀⢹⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⡇⠀⠀⠀⠀⠈⢻⣇⠞⣐⣤⠩⢹⠂⠀⠲⠀⢠⡞⢁⡀⣉⠉⠁⠨⠀⢀⠤⠉⠛⠃⢾⠀⠠⠴⣳⢉⣻⡟⠀⠀⢠⣷⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡇⠀⠀⠀⠀⠀⣆⢻⣾⣣⠈⠁⡄⠒⢿⠉⢠⠏⠀⢶⠠⡴⠛⠃⢑⣽⡩⢴⣬⣅⣀⠸⡆⠈⢼⢺⣼⠏⠀⠀⠀⢨⡿⡇⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⣿⡇⠀⠀⠀⠀⠀⢸⠈⡛⢻⣶⣄⡼⡚⢤⠁⠛⠀⠀⠾⠳⠦⢤⣄⣀⣀⣀⣀⣤⣯⣽⡳⢿⡀⢖⣻⠋⠀⠀⠀⠀⢀⡇⣧⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣤⣴⣾⣿⠁⠀⠀⠀⠀⠀⣿⠨⠀⠀⠘⠻⣿⣾⡌⠓⣧⡄⠀⠀⡀⠀⠀⠰⢦⠶⡦⠤⠾⢭⠳⢿⡲⣔⣶⣿⠀⠀⠀⠀⠀⣸⣣⡟⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣀⣠⣶⣾⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⣘⡋⣀⢃⡡⠙⠦⠰⠙⣿⣄⡌⠩⠁⣄⠐⠢⡌⠖⢀⢀⡤⠄⡠⣀⢰⠤⢹⣷⣽⡫⣄⠀⣠⢔⣫⠴⠋⠀⠀⠀⠀⠀⠀
⠀⠀⠀⣰⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠸⣍⣒⡉⠊⣩⠦⠓⢀⠘⠹⣿⣧⡁⡶⠀⠀⠹⠀⡴⠂⠀⠋⢰⠒⠘⣤⣼⡋⠀⠉⠲⡿⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⣠⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⣀⣤⡶⠉⣂⠒⠁⠀⢈⡂⢄⠀⠈⠸⡻⡷⢦⣤⣸⣁⣀⣈⣄⣀⣠⣴⣾⣿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣥⣀⠀⠀⠀⠀⣾⠋⠀⠀⠀⠀⠀⠙⠀⠱⠝⢢⠉⠙⠆⠑⠟⣇⠠⠉⠉⠈⢙⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣾⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠈⠢⡄⠀⠘⠧⣄⠀⠀⠀⠙⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠀⠁⠀⠈⠀⠁⢀⣠⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣶⣦⣤⣀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡶⠦⢤⣴⣖⣲⣄⣀⡀⢀⣠⠤⢤⣀⣤⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⢘⠳⡶⠾⠿⡿⠿⠿⡭⢉⣩⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

2024-10-29 14:02 UTC, m00ncr4wler commented
Awesome job so far 👍

2024-10-30 07:01 UTC, amishratnasthapit commented
Really looking forward to this feature.

2024-11-21 11:44 UTC, jamesgeorge007 requested changes
Great work, leaving a couple of edge cases/UX improvements encountered while testing the flows below:

- Attempting to run an empty collection should be prevented. An error toast is displayed for root collections under personal workspace though not consistent, but not extended to child collections. At the same time, it has to be accounted for collections at all levels under shared workspaces.

  There's also an edge case with root collections under the personal workspace where the error toast is still displayed despite creating requests within it at times.

  ![image](https://github.com/user-attachments/assets/b200651c-0cb3-4ac8-a838-5bc4a900a20f)

- Say, a collection run is initiated. Now, if the requests get deleted resulting in an empty collection, a corresponding empty state would be nice to have in the test runner tab open.

  ![image](https://github.com/user-attachments/assets/539c7ee6-e706-4295-ade0-b3f921adc674)

- If the collection corresponding to the test runner tab gets deleted there is no feedback currently and the below error gets logged to the console:

  ![image](https://github.com/user-attachments/assets/9bd00537-75bb-4c93-acbf-70f40bee0430)

- We could employ empty states for the `Passed` & `Failed` tabs when no tests exist in the requests getting executed.

  ![image](https://github.com/user-attachments/assets/fb8ba3e6-5ec0-4b8a-ae20-ecee8a976f42)

- If a request has an invalid endpoint, issues with scripts, running via the interceptor set to `Proxy` outside hoppscotch.io, etc, that could lead to an error running the collection, the corresponding request error state appears across the `Passed` and `Failed` tabs.

  <img width="1509" alt="image" src="https://github.com/user-attachments/assets/24a8b8d4-4249-4cde-b0aa-5cd871763fe7">

- Consider a collection with a request within it. Adding requests under the above collection would open the same in a new tab. Now, clicking on the same request will keep opening it in multiple tabs. This is observed for requests being added after initiating a collection run.

- In the test run tab, only the immediate parent collection name is displayed although there's a visual cue regarding the overall hierarchy. It'd be nice to display the collection tree or convey the full path to the request executed.

  <img width="1506" alt="image" src="https://github.com/user-attachments/assets/8351d466-c677-48d6-8c7a-e30510e6307e">

- There's a schema mismatch reported with a test run tab open against the key `restTabState` and performing a page reload. At times, the above tab gets closed during page reload.

- The response selected for any request from the previous collection run persists while initiating another run.

  <img width="1509" alt="image" src="https://github.com/user-attachments/assets/f34b80ac-a5dc-48de-a698-35424637d4d6">

- Specifying a slightly large delay in the run configuration and attempting to stop the run in between it is observed that the intermediary request stays in an infinite loading state.

  <img width="1506" alt="image" src="https://github.com/user-attachments/assets/66130512-f31a-40dd-909f-4fabd98b9cca">

- Running a collection with authorization and headers specified at the collection level isn't inherited by requests as expected. Try importing [this collection](https://github.com/anwarulislam/hoppscotch/blob/main/packages/hoppscotch-cli/src/__tests__/e2e/fixtures/collections/collection-level-auth-headers-coll.json) and observe the requests succeed while executing individually and not during the collection run.

- While selecting `New Run`, persisting the active `Delay` value might be helpful with a fallback to `500ms`. Also, entering a negative or decimal value for the `Delay` field should be prevented.

- Checking `Stop run if an error occurs` under run configuration and in case a request has syntax errors with the post-request script, the execution isn't halted and proceeds to completion. Also, do we want to report such a case under `Failures`, or keep it exclusive to failed test cases?

  <img width="1505" alt="image" src="https://github.com/user-attachments/assets/c0024619-34f4-479c-af18-0758442f598c">

- Say, there's a typo in the post request script for a request with the `toBeLevel()` scripting API method usage, it isn't reported as a failure. This is a pre-existing issue with the scripting side.

```js
// Check status code is 3xx
pw.test("Status code is 3xx", ()=> {
    // `status` instead of `status`
    pw.expect(pw.response.statu).toBeLevel3xx();
});
```

    <img width="1502" alt="image" src="https://github.com/user-attachments/assets/5462025c-5166-4511-981f-e7e40de1d6c7">

- Is it intentional that having a test runner tab open and attempting a new run from the collection tree opens another tab instead of picking the existing one?

I've pushed a [quick change](https://github.com/hoppscotch/hoppscotch/pull/3600/commits/679e809ea6a6e05d44ebe49f5cf26f082bbc3dbe) resolving schema mismatch errors with personal collections. Also, please look into the failing CLI tests.

2024-11-21 11:44 UTC, jamesgeorge007 commented on packages/hoppscotch-selfhost-web/src/platform/collections/collections.platform.ts
> +      // loadUserCollections("REST")
Could you elaborate on why `loadUserCollections` is commented out? Is anything remaining here with the TODO resolution?

2024-11-26 10:20 UTC, jamesgeorge007 approved these changes
The remaining issues are to be handled separately.

2024-11-26 10:23 UTC, nivedin approved these changes
LGTM 💯

2024-11-26 10:26 UTC, merged

2024-11-28 16:41 UTC, jamesgeorge007 commented
Collection runner is now live with [v2024.11.0](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.11.0).