Update user.service.ts
hoppscotch/hoppscotch pull request #3632
Opened 2023-12-07 10:51 UTC by mirishfaq-logicparadise

i have made changes to the convertDbUserToUser function removed the unnecessary ternary operator and introduced simple null coalescing,  
instead of this     return {
      ...dbUser,
      currentRESTSession: JSON.stringify(dbCurrentRESTSession) ?? null,
      currentGQLSession:  JSON.stringify(dbCurrentGQLSession) ?? null,
    };
we are simply doing this 
return {...dbUser,dbCurrentRESTSession
        ? JSON.stringify(dbCurrentRESTSession)
        : null,
      currentGQLSession: dbCurrentGQLSession
        ? JSON.stringify(dbCurrentGQLSession)
        : null}

Closes # 

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### Additional Information

2024-01-12 07:31 UTC, balub approved these changes
Please make sure the lastest commits are present in the PR.

2024-01-12 08:43 UTC, mirishfaq-logicparadise commented
okay will do the same

2024-01-13 10:23 UTC, mirarifhasan approved these changes
LGTM

2024-01-17 10:14 UTC, mirarifhasan requested changes

2024-01-17 10:14 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/user/user.service.ts
> +      currentGQLSession:  JSON.stringify(dbCurrentGQLSession) ?? null,
`dbCurrentRESTSession` can be null.
`JSON.stringify(null)` will return `"null"` as string data-type, which breaks the contract.

Same goes for `dbCurrentGQLSession`.

2024-01-18 04:34 UTC, closed without merging