fix: documentation is not being generated on GQL
hoppscotch/hoppscotch pull request #3730
Opened 2024-01-07 20:46 UTC by anwarulislam

Closes HFE-380

### Description
Updated the `resolveRootType` function to correctly handle GraphQL types that do not have an `ofType` property. The function now uses a while loop to traverse the `ofType` chain until it reaches a type that does not contain any other types (i.e., its ofType property is null). This ensures that the function always returns the correct root type for any given GraphQL type.

- [ ] Not Completed
- [x] Completed

2024-01-08 08:26 UTC, Timeraa commented
Encountered this issue as well when I was working on #3723, glad I wasn't the only one

2024-01-17 14:38 UTC, amk-dev requested changes
there is a method from the `graphql` package `getNamedType` that does the same thing as `resolveRootType`. can we use that instead of `resolveRootType`

https://graphql.org/graphql-js/type/#getnamedtype

2024-01-17 14:56 UTC, liyasthomas commented
Updated to `getNamedType` instead of `resolveRootType`.

2024-01-17 15:19 UTC, amk-dev approved these changes

2024-01-18 06:29 UTC, jamesgeorge007 approved these changes

2024-01-23 16:30 UTC, merged