feat: upgraded user management in admin dashboard
hoppscotch/hoppscotch pull request #3814
Opened 2024-02-08 15:03 UTC by JoelJacobStephen

### Ticket
Closes HFE-406

### Description
This PR brings a ton of features to improve user management in Admin Dashboard. 

### New Features
1. Admins can now update the name of any user,
2. Bulk actions are now possible in the users table. These actions include:
	- Elevation of multiple users to admin status,
	- Removal of admin status from multiple users,
	- Deletion of multiple users,
3. Ability to search through the users table by name or email address of the users.
4. New page based pagination system for the users table replacing the previous used scroll based pagination system.
5. Ability to revoke pending invites from the pending invites page.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2024-03-08 17:21 UTC, jamesgeorge007 requested changes
Search and pagination don't play well in the user list view. The computation for total pages doesn't account for search in all cases.

2024-03-09 05:40 UTC, JoelJacobStephen commented
> Search and pagination don't play well in the user list view. The computation for total pages doesn't account for search in all cases.

@jamesgeorge007 I've fixed the issue. You can test it now.

2024-03-09 14:28 UTC, jamesgeorge007 requested changes
- A search session has to ensure the page number gets reset to `1`.
- At times the entire list gets populated while clearing the search entry at once.

2024-03-10 06:02 UTC, JoelJacobStephen commented
> * A search session has to ensure the page number gets reset to `1`.
> * At times the entire list gets populated while clearing the search entry at once.

@jamesgeorge007 I have resolved these issue.

2024-03-12 04:35 UTC, jamesgeorge007 commented on packages/hoppscotch-sh-admin/src/pages/users/index.vue
There's an issue arising here while changing the admin status (making a user admin & vice versa) for a user and immediately selecting the row for which the action was performed won't result in the action bar (with toggle admin & delete actions) to show up. It shows up only during the second attempt.

2024-03-12 14:21 UTC, jamesgeorge007 approved these changes
LGTM 🚀 
Leaving a few pointers below for future reference.

2024-03-12 14:21 UTC, jamesgeorge007 commented on packages/hoppscotch-sh-admin/src/pages/users/index.vue
> +          :loading="showSpinner"
There's a slight difference in height compared to the spinner and the row with actual data. We could leverage the `loading-state` slot to implement a custom spinner to fine-tune the dimensions.

2024-03-12 14:22 UTC, jamesgeorge007 commented on packages/hoppscotch-sh-admin/src/pages/users/index.vue
This requires an update to [@hoppscotch/ui](https://github.com/hoppscotch/ui) and will be handled separately.

2024-03-13 09:01 UTC, nivedin requested changes

2024-03-13 09:15 UTC, merged

2024-03-13 10:18 UTC, jamesgeorge007 commented on packages/hoppscotch-sh-admin/src/pages/teams/index.vue
> +          @onRowClicked="goToTeamDetails"
@JoelJacobStephen, please make a note of these to address separately.