hotfix: request variable version syncing bug
hoppscotch/hoppscotch pull request #3889
Opened 2024-03-11 07:53 UTC by nivedin

Closes HFE-443

### Description
This PR fixed the issue with request variable where the app crashes since the request schema failed to upgrade version while syncing returning a undefined value.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2024-03-11 09:17 UTC, jamesgeorge007 requested changes
We have to account for the case when a collection conforming to the old version format is imported and a request is chosen from the collection tree straightaway.

2024-03-11 10:22 UTC, nivedin commented on packages/hoppscotch-data/src/collection/index.ts
there is case where a collection version is upto date but the request version will be behind in this case the translate will not return the latest schema. So the version check is removed here.
cc @AndrewBastin

2024-03-11 16:46 UTC, jamesgeorge007 approved these changes

2024-03-11 17:24 UTC, AndrewBastin commented on packages/hoppscotch-data/src/collection/index.ts
Actaully these can be updated to use Verzod functions now. Since it can perform validations as well ?

2024-03-12 04:29 UTC, jamesgeorge007 commented on packages/hoppscotch-data/src/collection/index.ts
I think we'll have to separate them into REST & GQL implementations for better control and update the transformation functions accordingly.

2024-03-12 06:12 UTC, merged