feat: first time user spotlight animation
hoppscotch/hoppscotch pull request #3977
Opened 2024-04-15 07:26 UTC by nivedin

Closes HFE-476

### Description
This PR adds animation to the spotlight search component.

https://github.com/hoppscotch/hoppscotch/assets/53208152/efbbb320-1d5d-4711-9dcb-a8dd7dcca664

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2024-04-16 12:08 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/components/app/SpotlightSearch.vue
> +  { text: '"Selecting a Request"', show: true },
Can we use i18n strings here instead?

2024-04-16 12:11 UTC, JoelJacobStephen requested changes
The animation will stop once the user clicks on the spotlight for the first time. However it does not stop if the user uses the shortcut to invoke the spotlight. I think we should also toggle `HAS_OPENED_SPOTLIGHT` when the user uses the shortcut to invoke the spotlight.

2024-04-16 12:13 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/components/app/SpotlightSearch.vue
> +          Try
We can use i18n strings here as well

2024-04-16 12:15 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/components/app/SpotlightSearch.vue
> +              v-for="(word, index) in wordToShow"
We are showing a phrase/sentence here.  A better naming would be `phrasesToShow` in my opinion.

2024-04-16 12:15 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/components/app/SpotlightSearch.vue
> +const showNextWords = () => {
A better name would be `showNextPhrase`

2024-04-16 19:05 UTC, nivedin commented on packages/hoppscotch-common/src/components/app/SpotlightSearch.vue
> +  { text: '"Selecting a Request"', show: true },
yes

2024-04-17 12:10 UTC, JoelJacobStephen requested changes
Feature wise, everything is working as expected. I have suggested minor code improvements. Once they are resolved, it's good to go from my end.

2024-04-18 07:06 UTC, nivedin commented on packages/hoppscotch-common/src/services/spotlight/searchers/collections.searcher.ts
>          } else if (pageCategory === "graphql") {
yeah good catch.. patched

2024-04-18 07:28 UTC, JoelJacobStephen approved these changes
LGTM!! 💯

2024-04-22 05:25 UTC, AndrewBastin approved these changes

2024-04-22 06:51 UTC, merged

2024-10-09 13:28 UTC, chlab commented
I was about to open an issue complaining about this animation as it's kind of distracting when keeping hoppscotch open on a secondary display and something keeps trying to get your attention :). While searching for existing issues I found this and realized I can just use the search once to turn it off.

Just wanted to drop in and say thank you for being considerate/mindful enough to turn it off once the search was used! ❤️  And while I'm at it, thanks to all HS contributors for a great API client!