refactor: switch workspace after creation
hoppscotch/hoppscotch pull request #4015
Opened 2024-04-29 14:10 UTC by nivedin

Closes HFE-483

### Description
This PR add's a minor improvement in the workspace creation flow where the workspace is automatically switched to the created one.

### Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2024-04-30 05:29 UTC, JoelJacobStephen requested changes
@nivedin When a new workspace is created, the dropdown which allows users to switch workspaces is not updated. Even after switching to the personal workspace, it is not updated.

https://github.com/hoppscotch/hoppscotch/assets/70131076/9dc8268d-b55b-49da-8f04-17bae1d98d28

2024-04-30 05:29 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/components/teams/Add.vue
> +            if (props.switchWorkspaceAfterCreation) {
We are having two same if checks here. Please remove one

2024-05-07 05:44 UTC, JoelJacobStephen requested changes
There are few type issues and some unnecessary imports in few components such as `SaveRequest.vue`. Rest looks good to me. Also please bring in the latest changes from `release/2024.3.3` to this PR.

2024-05-07 05:44 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/components/teams/Add.vue
> +            role: team.myRole,
Resolve type issue

2024-05-07 05:44 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/components/workspace/Selector.vue
> +    role: team.myRole,
Resolve type issue here.

2024-05-07 05:44 UTC, JoelJacobStephen commented on packages/hoppscotch-common/src/components/environments/index.vue
>  import { Environment } from "@hoppscotch/data"
You can remove the unnecessary imports

2024-05-07 07:12 UTC, JoelJacobStephen approved these changes
LGTM!! 💯

2024-05-08 13:20 UTC, amk-dev approved these changes
LGTM 🚀

2024-05-09 14:58 UTC, merged