fix(sh-admin): saving changes to server configurations post a failed attempt will require a page reload in dashboard
hoppscotch/hoppscotch pull request #4081
Opened 2024-05-22 13:13 UTC by JoelJacobStephen

### Ticket
- Closes HFE-515

### Description
This PR addresses an issue on the admin dashboard where, when an attempt is made to change server configurations and a mutation error has occurred, after the relevant error toast is displayed, any subsequent attempts to save additional changes to configs fail to trigger the server restart and confirmation modals. This prevents users from making further changes unless they reload the page. This issue is resolved in this PR.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2024-05-23 16:50 UTC, nivedin approved these changes

2024-05-24 13:27 UTC, jamesgeorge007 requested changes
A failed reset server configuration attempt will still display the modal with the countdown timer.

https://github.com/hoppscotch/hoppscotch/assets/25279263/8c67639a-a1ed-430f-8941-6a4fba2d430a

2024-05-24 13:27 UTC, jamesgeorge007 commented on packages/hoppscotch-sh-admin/src/components/settings/ServerRestart.vue
> +    if (!dataSharingResult) emit('mutationFailure');
We'll have to return early after emitting the event. Currently, the control flow will proceed with the timer resulting in a page reload after `30s`.

2024-05-25 13:22 UTC, JoelJacobStephen commented
> A failed reset server configuration attempt will still display the modal with the countdown timer.
> 
>  Screen.Recording.2024-05-24.at.6.39.36.PM.mov

@jamesgeorge007 I have resolved the issue

2024-05-27 08:48 UTC, jamesgeorge007 approved these changes
Pushed a [commit](https://github.com/hoppscotch/hoppscotch/pull/4081/commits/05ae344bd46ff83299d40084fceaa3dc09b8024e) ensuring attempts go through after a failed reset configuration action along with some refactoring.

2024-06-03 09:01 UTC, merged