feat: new ui for response interface generation
hoppscotch/hoppscotch pull request #4105
Opened 2024-06-05 10:20 UTC by anwarulislam

### Description
Response interface generation new UI added in the sidebar

### Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2024-06-18 10:19 UTC, nivedin requested changes
- can we hide the response interface type section if the response is null

![image](https://github.com/hoppscotch/hoppscotch/assets/53208152/fdbdb17a-11ce-400b-8cd1-b412b900664f)
- the interface section layout height changes each time, also the component crashes sometime

https://github.com/hoppscotch/hoppscotch/assets/53208152/50b07f01-2079-4bd3-94f1-a477be2b704e

2024-06-18 10:27 UTC, liyasthomas commented
I see some caveats for this design hence I'll review this and give comments internally over Slack.

2024-08-29 14:41 UTC, anwarulislam commented on packages/hoppscotch-common/src/components/app/PaneLayout.vue
> +        :horizontal="COLUMN_LAYOUT || forceColumnLayout"
I experimented with different implementations in the past, but now I don't think it's necessary. However, I believe it's good to have for the future.

2024-08-29 15:28 UTC, nivedin approved these changes
LGTM 💯

2024-08-30 06:40 UTC, merged