refactor(sh-admin): new invite links flow for admin dashboard
hoppscotch/hoppscotch pull request #4176
Opened 2024-07-09 12:50 UTC by JoelJacobStephen

### Ticket

### Description
This PR focuses on improving the current invite links flow in the admin dashboard.

### Changes Introduced
- New Success Invite Modal introduced which makes the action that was performed to be made clear to the user and help to take further action
- Users can copy the invite link from the newly introduced modal

### Objectives
- [x] When the admin performs a single invite, regardless of the SMTP status
- [ ] Change the copy "Send Invite" to "Add user" 
- [ ] Remove the "copy link" button
- [ ] When the user enters an email and clicks on add user show a confirmation modal with the below info depending on the cases
- *Case 1:* If SMTP is enabled, an email is sent and admins can copy the invite link
- *Case 2:* If SMTP is disabled, admins can copy the invite link 	

### Screenshot

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2024-07-22 10:35 UTC, nivedin requested changes
why do we need a `Copy Link` button in the users/invited page ?

![image](https://github.com/user-attachments/assets/6130ad65-efcd-4c51-8646-c012100c4f55)

also its visible in empty state as well
![image](https://github.com/user-attachments/assets/082163a9-b950-494b-990d-222ba3655600)

2024-07-22 10:51 UTC, nivedin requested changes

2024-07-22 10:51 UTC, nivedin commented on packages/hoppscotch-sh-admin/src/pages/users/index.vue
> +    </HoppSmartModal>
we can convert this to a modal component

2024-07-23 13:49 UTC, JoelJacobStephen commented
> why do we need a `Copy Link` button in the users/invited page ?
> 
> ![image](https://private-user-images.githubusercontent.com/53208152/350933290-6130ad65-efcd-4c51-8646-c012100c4f55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDA2ODEsIm5iZiI6MTcyMTc0MDM4MSwicGF0aCI6Ii81MzIwODE1Mi8zNTA5MzMyOTAtNjEzMGFkNjUtZWZjZC00YzUxLTg2NDYtYzAxMjEwMGM0ZjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEzMTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4Y2Y4Y2RjMzljNDZmY2RkMzFmOWYyZTNjYTJkNjI5OWZhYzA1MWYzMDViZTA2YmM0YTExYTJiMTU5YjMzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xfx5k_dcqqpN6KIIJdgORLK6VoWPgeoRto8hKH6NAZU)
> 
> also its visible in empty state as well ![image](https://private-user-images.githubusercontent.com/53208152/350933463-082163a9-b950-494b-990d-222ba3655600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDA2ODEsIm5iZiI6MTcyMTc0MDM4MSwicGF0aCI6Ii81MzIwODE1Mi8zNTA5MzM0NjMtMDgyMTYzYTktYjk1MC00OTRiLTk5MGQtMjIyYmEzNjU1NjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEzMTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZTM4ZjllYjk2YWU5YTYxMTgyNGU4MGU3MjlkNmE5NjlkOWI3ZmRkZThkOTAwNDc3MjQyNWJmMWVmZDEwOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1p9VdY286796V0T1vNmtwSAsqcpVjcsTZZNOEd4i4k)

@nivedin The link for all the invites shown is the same which is the `baseURL`. That is why there is a signle copy link button. I have now removed copy link button when there are no pending invites.

2024-07-23 14:34 UTC, nivedin commented
> > why do we need a `Copy Link` button in the users/invited page ?
> > ![image](https://private-user-images.githubusercontent.com/53208152/350933290-6130ad65-efcd-4c51-8646-c012100c4f55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDA2ODEsIm5iZiI6MTcyMTc0MDM4MSwicGF0aCI6Ii81MzIwODE1Mi8zNTA5MzMyOTAtNjEzMGFkNjUtZWZjZC00YzUxLTg2NDYtYzAxMjEwMGM0ZjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEzMTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4Y2Y4Y2RjMzljNDZmY2RkMzFmOWYyZTNjYTJkNjI5OWZhYzA1MWYzMDViZTA2YmM0YTExYTJiMTU5YjMzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xfx5k_dcqqpN6KIIJdgORLK6VoWPgeoRto8hKH6NAZU)
> > also its visible in empty state as well ![image](https://private-user-images.githubusercontent.com/53208152/350933463-082163a9-b950-494b-990d-222ba3655600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDA2ODEsIm5iZiI6MTcyMTc0MDM4MSwicGF0aCI6Ii81MzIwODE1Mi8zNTA5MzM0NjMtMDgyMTYzYTktYjk1MC00OTRiLTk5MGQtMjIyYmEzNjU1NjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDEzMTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZTM4ZjllYjk2YWU5YTYxMTgyNGU4MGU3MjlkNmE5NjlkOWI3ZmRkZThkOTAwNDc3MjQyNWJmMWVmZDEwOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1p9VdY286796V0T1vNmtwSAsqcpVjcsTZZNOEd4i4k)
> 
> @nivedin The link for all the invites shown is the same which is the `baseURL`. That is why there is a signle copy link button. I have now removed copy link button when there are no pending invites.

okay gotcha, can we maybe change the text to `Copy Invite Link` or something, its difficult to understand the context wdyt @liyasthomas

2024-07-24 14:39 UTC, JoelJacobStephen commented
@nivedin I've changed the button text to `Copy Invite Link` after taking approval from @liyasthomas. I have pushed the changes.

2024-07-25 08:29 UTC, nivedin approved these changes

2024-07-26 14:44 UTC, merged