refactor: created versioned entities for global environments
hoppscotch/hoppscotch pull request #4216
Opened 2024-07-28 09:35 UTC by ipalakchopra

Partly Closes #4160. 
This PR intends to update the Global Environments Schema to be a versioned entity.
### Description
- Integrate Verzod into Global Environments.
- Create 2 versions as specified in the issue.
### Checks
- [x] My pull request adheres to the code style of this project.
- [ ] My code completes the issue.
- [ ] My code requires changes to the documentation.

2024-08-02 17:11 UTC, jamesgeorge007 requested changes
Once the proposed schema changes are in place, the existing usages have to be extended to consume the `GlobalEnvironment` versioned entity:

- For the [persistence service](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-common/src/services/persistence/index.ts#L628-L651), update the maintained schema to be based on the versioned entity.

```diff
     // Validate data read from localStorage
-    const result = GLOBAL_ENV_SCHEMA.safeParse(globalEnvData)
-    if (result.success) {
-      globalEnvData = result.data
+    const result = GlobalEnvironment.safeParse(globalEnvData)
+    if (result.type === "ok") {
+      globalEnvData = result.value
     } else {
       this.showErrorToast(globalEnvKey)
       window.localStorage.setItem(
         `${globalEnvKey}-backup`,
         JSON.stringify(globalEnvData)
       )
     } 
-    setGlobalEnvVariables(globalEnvData as Environment["variables"])
+    setGlobalEnvVariables(globalEnvData)
```

- Update the [default state for global environments](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-common/src/newstore/environments.ts#L34) at the store from an empty array to `{ v: 1, variables: [] }`. We're changing the store representation since it effectively gets written to `localStorage` and needs to conform to the schema. Necessary changes have to be made to the relevant [dispatcher methods](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-common/src/newstore/environments.ts#L280-L314) following this. For instance, the case with `setGlobalVariables`:

```diff
-  setGlobalVariables(_, { entries }: { entries: Environment["variables"] }) {
+  setGlobalVariables(_, { entries }: { entries: GlobalEnvironment }) {
     return {
       globals: entries,
     }
```

- While fetching global environments in the [syncing context](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-selfhost-web/src/platform/environments/environments.platform.ts#L99-L106) (sync actions in the personal workspace and pulls data from upstream while the app boots and writes to `localStorage`), we'll have to bring in the `GlobalEnvironment` versioned entity to translate any data conforming to the old format (`v0`) to the latest version (`v1`).

> [verzod](https://github.com/AndrewBastin/verzod) needs to be added as a dependency under `packages/hoppscotch-selfhost-web` and the `entityReference` function has to be imported from the same.

```diff
     if (globalEnv) {
+      const globalEnvVariableEntries = JSON.parse(globalEnv.variables)
+
+      const result = entityReference(GlobalEnvironment).safeParse(
+        globalEnvVariableEntries
+      )
+
       runDispatchWithOutSyncing(() => {
-        setGlobalEnvVariables(JSON.parse(globalEnv.variables))
+        setGlobalEnvVariables(
+          result.success ? result.data : globalEnvVariableEntries
+        )
         setGlobalEnvID(globalEnv.id)
       })
     }
``` 

The above steps need to be extended for the [SH Desktop app](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-selfhost-desktop/src/platform/environments/environments.platform.ts#L98-L105) as well.

2024-08-02 17:11 UTC, jamesgeorge007 commented on packages/hoppscotch-data/src/global-environments/index.ts
> +>["variables"][number]
Anything appearing below can be removed.

2024-08-02 17:11 UTC, jamesgeorge007 commented on packages/hoppscotch-data/src/global-environments/index.ts
Let's rename the directory to `global-environment`.

2024-09-11 09:43 UTC, jamesgeorge007 approved these changes

2024-09-17 09:32 UTC, nivedin approved these changes

2024-09-23 11:31 UTC, merged