feat: duplicate global environments under team workspaces
hoppscotch/hoppscotch pull request #4334
Opened 2024-09-09 05:49 UTC by jamesgeorge007

Duplicate global environment action was specific to the personal workspace where the entries were added and hidden while at a team workspace with #4245. This PR aims to extend support to team workspaces and re-enabling the action.

Closes HFE-575.

### What's changed

- Adds a new prop `duplicateGlobalEnvironmentLoading` (keeps track of the n/w call status and dismisses the context menu) and defines a new event `duplicate-global-environment` under the `EnvironmentsMyEnvironment` component.
- Relevant additions under the root `Environments` component to trigger the `createTeamEnvironment` GQL mutation with the global environment variables in scope.
- Adds a new helper function `getEnvActionErrrorMessage` abstracting the error messages reused across for environment-related actions.

### Notes to reviewers

Please ensure to cross-check the error message updates once with the newly added helper function.

2024-09-10 12:15 UTC, nivedin approved these changes
LGTM 💯

2024-09-11 07:10 UTC, balub requested changes
I think the FE does not subscribe to the environment-created subscription, I need to reload the screen for the newly created environment to pop up. 

https://github.com/user-attachments/assets/29341f56-5be1-49af-8eb6-6819dadb0e01


@jamesgeorge007 can you confirm ??

2024-09-11 07:37 UTC, jamesgeorge007 commented
> I think the FE does not subscribe to the environment-created subscription, I need to reload the screen for the newly created environment to pop up.
> 
>  WhatsApp.Video.2024-09-11.at.12.44.47_6383bb3c.mp4 
> @jamesgeorge007 can you confirm ??

Discussed separately, it was found specific to the local environment setup.

2024-09-16 11:55 UTC, balub approved these changes
LGTM 🚀

2024-09-25 12:44 UTC, merged