chore: addition of new GQL subscription for `UserCollection` duplication
hoppscotch/hoppscotch pull request #4358
Opened 2024-09-18 19:28 UTC by balub

Closes HSB-476

### What's changed

In this PR we add a new GQL subscription `userCollectionDuplicated` which returns the entire UserCollection tree when subscribed to.

### Notes to reviewers

Nil

2024-09-19 09:24 UTC, jamesgeorge007 commented on packages/hoppscotch-backend/src/user-collection/user-collection.service.ts
> +    isCollectionDuplication = true,
```suggestion
    isCollectionDuplication = false,
```

2024-09-19 09:24 UTC, jamesgeorge007 commented on packages/hoppscotch-backend/src/user-collection/user-collection.service.ts
>      );
We require only the `.../duplicated` topic to be published during a duplicate action. Also, shouldn't the check be the other way around where the `.../duplicated` topic is published if `isCollectionDuplication` is set to `true`?

```suggestion
    if (isCollectionDuplication) {
      const collectionData = await this.fetchCollectionData(
        userCollections[0].id,
      );

      if (E.isRight(collectionData))
        this.pubsub.publish(
          `user_coll/${userID}/duplicated`,
          collectionData.right,
        );
    } else {
      userCollections.forEach((collection) =>
        this.pubsub.publish(
          `user_coll/${userID}/created`,
          this.cast(collection),
        ),
      );
    }
```

2024-09-19 09:24 UTC, jamesgeorge007 commented on packages/hoppscotch-backend/src/user-collection/user-collection.service.ts
> +  private async fetchCollectionData(collectionID: string) {
Noticed the return type wasn't getting inferred correctly and might want to specify it.

```suggestion
  private async fetchCollectionData(
    collectionID: string,
  ): Promise<E.Left<string> | E.Right<UserCollectionDuplicatedData>> {
```

2024-09-19 09:26 UTC, jamesgeorge007 commented on packages/hoppscotch-backend/src/user-collection/user-collection.service.ts
> +      false,
```suggestion
      true,
```

2024-09-23 06:26 UTC, mirarifhasan requested changes

2024-09-23 06:26 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/user-collection/user-collection.resolver.ts
> +import { any } from 'jest-mock-extended';
Remove unused imports

2024-09-25 09:04 UTC, jamesgeorge007 approved these changes

2024-09-25 09:04 UTC, jamesgeorge007 commented on docker-compose.yml
Please be sure to revert these changes before merging.

2024-09-26 14:51 UTC, mirarifhasan approved these changes
LGTM

2024-09-26 17:14 UTC, jamesgeorge007 approved these changes

2024-09-26 17:24 UTC, merged