feat: add button to export test results as json
hoppscotch/hoppscotch pull request #4419
Opened 2024-10-08 21:01 UTC by Pranay-Pandey

Closes #4328 

Add a button next to test results to export the test results as a JSON file.

### What's changed

Added a share icon next to trash icon in the test results tray.
Added a new file to export the test Results to a json.

### Notes to reviewers

2024-10-10 12:13 UTC, nivedin requested changes

2024-10-10 12:13 UTC, nivedin commented on packages/hoppscotch-common/src/components/http/TestResult.vue
> +const share = () => {
change this function name to `downloadTestResult`

2024-10-10 12:13 UTC, nivedin commented on packages/hoppscotch-common/src/helpers/import-export/export/testResults.ts
> +export const ExportTestResults = async (testResults: HoppTestResult) => {
we generally use `camel case` naming convention for function naming, you can change this to `exportTestResults`

2024-10-21 12:28 UTC, Pranay-Pandey commented
@nivedin Thank you for your review. I have changed the function names. Please let me know if some other part needs revision as well

2024-10-22 12:18 UTC, nivedin approved these changes

2024-10-28 15:53 UTC, merged