Configured CORS for Development and Production
hoppscotch/hoppscotch pull request #4430
Opened 2024-10-12 06:15 UTC by ZenMachina16

Closes #4199

### Introduction
This pull request addresses the issue of identical CORS settings being used in both development and production environments. It refines the logic in the backend to differentiate the CORS configuration based on the environment (development vs. production).

### What's changed
- [x] **Modified CORS settings**: Updated the `if` and `else` blocks in the file `hoppscotch-backend/src/main.ts` to ensure the CORS settings are differentiated for development and production.
  - In development (`if` block), more permissive CORS settings are applied for easier testing.
  - In production (`else` block), restricted CORS settings are applied to enhance security.
- [x] **Code cleanup**: Removed redundant code that caused identical settings to be applied for both environments.

### Notes to reviewers
- The changes maintain backward compatibility by ensuring the development environment retains flexibility while securing the production environment.
- Tested locally to ensure proper CORS behavior for both environments.
- Let me know if additional changes are needed, or if there are any specific configurations you'd like to refine further!

2025-05-13 09:40 UTC, mirarifhasan requested changes

2025-05-13 09:40 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/main.ts
> +  });
@ZenMachina16 
For `development` mode, allow all the origins.

2025-05-13 09:40 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/main.ts
> +    origin: configService.get('PROD_WHITELISTED_ORIGINS'),
Keep only one env variable `WHITELISTED_ORIGINS`.

2025-05-14 03:46 UTC, mirarifhasan approved these changes
Update a minor changes, LGTM

2025-05-14 06:59 UTC, jamesgeorge007 approved these changes

2025-05-14 06:59 UTC, merged