fix(graphql): add HttpResponseMeta component for GraphQL responses
hoppscotch/hoppscotch pull request #4435
Opened 2024-10-13 22:45 UTC by barrettluke

Closes #4395

What’s changed

	•	Added HttpResponseMeta to Response.vue to handle GraphQL responses for http.
	•	Commented out the redundant AppShortcutsPrompt in Response.vue since HttpResponseMeta now covers its functionality.
	•	Modified connection.ts in helpers/graphql to format the data for HttpResponseMeta.

Notes to reviewers

	•	The AppShortcutsPrompt was redundant with HttpResponseMeta, so it’s only commented out for now to preserve the original logic.
	•	Let me know if the data handling in connection.ts for HttpResponseMeta needs any adjustments.

2025-03-26 09:22 UTC, jamesgeorge007 requested changes

2025-03-26 09:22 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/components/graphql/Response.vue
> +    />
Is the conditional rendering necessary for this component, given it has necessary safeguards at the source, and the `AppShortcutsPrompt` component gets rendered accordingly? For instance, usage within the REST page is as follows:

https://github.com/hoppscotch/hoppscotch/blob/86c0bb619d9fc41484de08d2454242f1194d18bd/packages/hoppscotch-common/src/components/http/Response.vue#L3

Also, while you're at it, could you update the type contracts for the `response` prop extending to the GQL response documents?

https://github.com/hoppscotch/hoppscotch/blob/86c0bb619d9fc41484de08d2454242f1194d18bd/packages/hoppscotch-common/src/helpers/graphql/connection.ts#L56-L72

2025-03-26 09:22 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/components/graphql/Response.vue
> +    <!-- <AppShortcutsPrompt v-else class="p-4" /> -->
We can remove this based on the above proposal.

2025-03-26 09:22 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/helpers/graphql/connection.ts
> +    }
Let's follow the established conventions for the above computations as with the existing implementation for REST.

https://github.com/hoppscotch/hoppscotch/blob/86c0bb619d9fc41484de08d2454242f1194d18bd/packages/hoppscotch-common/src/helpers/kernel/rest/response.ts#L24-L54

2025-04-28 04:11 UTC, barrettluke commented on packages/hoppscotch-common/src/components/graphql/Response.vue
> +    <!-- <AppShortcutsPrompt v-else class="p-4" /> -->
Removed comment.

2025-04-28 04:14 UTC, barrettluke reviewed
Looks good.

2025-04-28 04:17 UTC, barrettluke commented on packages/hoppscotch-common/src/components/graphql/Response.vue
> +    />
I removed the condition

2025-04-28 04:27 UTC, barrettluke commented on packages/hoppscotch-common/src/components/graphql/Response.vue
> +    />
I believe the GQL response should be ok with the following [packages/hoppscotch-common/src/helpers/graphql/connection.ts](url)

2025-04-28 04:29 UTC, barrettluke commented on packages/hoppscotch-common/src/helpers/graphql/connection.ts
> +    }
The code base has had some changes and not sure if this is still needed. If so maybe this could be a separate ticket for refactoring.

2025-07-24 11:08 UTC, jamesgeorge007 approved these changes

2025-07-24 11:22 UTC, merged