feat(common): introducing ability to set custom collection import size limit
hoppscotch/hoppscotch pull request #4440
Opened 2024-10-15 23:42 UTC by JoelJacobStephen

### Ticket
- Closes HFE-615
- Fixes #4139 

### Description
This PR adds the ability to set custom collection import size limit and change it from the default value of 10MB. The size limit for selfhost-web will now be 50MB.

### Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

2024-10-16 11:41 UTC, jamesgeorge007 requested changes
Ideal candidates for `platformFeatureFlags` are boolean properties indicating whether a given feature applies to the active platform. In this case, it'd be appropriate to introduce the `collectionImportSizeLimit` property at the top-level platform definition or say, within a new field like `limits`.

@AndrewBastin, appreciate your thoughts on the convention here.

EDIT: Discussed separately, we'll be including the `collectionImportSizeLimit` property within a new `limits` field. This field can be extended to impose limits for file uploads with `multipart/form-data` content type when workspace syncing is enabled down the line.

2024-10-16 20:50 UTC, AndrewBastin commented
I guess, the limits field is not a bad idea, I actually recommended feature flags mostly because there was no clean place to put it and a category for just this limit is weird, are there any other limits that there is a chance for it to come up ?

2024-10-18 00:00 UTC, JoelJacobStephen commented
> Ideal candidates for `platformFeatureFlags` are boolean properties indicating whether a given feature applies to the active platform. In this case, it'd be appropriate to introduce the `collectionImportSizeLimit` property at the top-level platform definition or say, within a new field like `limits`.
> 
> @AndrewBastin, appreciate your thoughts on the convention here.
> 
> EDIT: Discussed separately, we'll be including the `collectionImportSizeLimit` property within a new `limits` field. This field can be extended to impose limits for file uploads with `multipart/form-data` content type when workspace syncing is enabled down the line.

@jamesgeorge007 I have implemented the new limits field.

2024-10-21 09:10 UTC, jamesgeorge007 approved these changes

2024-10-23 13:04 UTC, merged