fix(i18n): fixed translation errors and translated missing keys
hoppscotch/hoppscotch pull request #4455
Opened 2024-10-17 16:12 UTC by sawa-ko

Closes # 

### What's changed

Some translation errors are corrected and new corrections are added.

### Notes to reviewers

I also noticed that some keys that I had already translated have been put back into English, it's weird, so I had to translate them again.

2024-10-22 12:09 UTC, nivedin requested changes

2024-10-22 12:09 UTC, nivedin commented on packages/hoppscotch-common/locales/es.json
> +    "file_size_limit_exceeded_warning_multiple_files": "Los archivos seleccionados exceden el límite recomendado de 10MB. Sólo se importarán los primeros {ficheros} seleccionados.",
```suggestion
    "file_size_limit_exceeded_warning_multiple_files": "Los archivos seleccionados exceden el límite recomendado de 10MB. Sólo se importarán los primeros {files} seleccionados.",
```

should not change the variable name

2024-10-22 12:47 UTC, sawa-ko commented on packages/hoppscotch-common/locales/es.json
> +    "file_size_limit_exceeded_warning_multiple_files": "Los archivos seleccionados exceden el límite recomendado de 10MB. Sólo se importarán los primeros {ficheros} seleccionados.",
Oh yes, sorry

2024-10-22 17:12 UTC, nivedin requested changes
there are multiple strings with key name changed, please revert them

2024-10-22 17:12 UTC, nivedin commented on packages/hoppscotch-common/locales/es.json
> +      "redirect_no_token_punto final": "No se ha definido ningún punto final de token",
keep the key name same

2024-10-22 17:12 UTC, nivedin commented on packages/hoppscotch-common/locales/es.json
> +      "label_authorization_punto final": "Punto final de autorización",
keep the key name same

2024-10-22 17:12 UTC, nivedin commented on packages/hoppscotch-common/locales/es.json
> +      "label_token_punto final": "Punto final de token",
keep the key name same

2024-10-22 17:12 UTC, nivedin commented on packages/hoppscotch-common/locales/es.json
> +    "punto final": "El punto final no puede estar vacío",
keep the key name same

2024-10-23 05:36 UTC, sawa-ko commented
Oh no, my "replace everything" went wrong. I'll fix everything. 🥲

2024-10-24 16:08 UTC, nivedin approved these changes

2024-10-25 08:14 UTC, jamesgeorge007 approved these changes

2024-10-25 08:20 UTC, merged