feat: one-click graphQL query & mutation generation
hoppscotch/hoppscotch pull request #4483
Opened 2024-10-27 06:21 UTC by bogking

Closes #4371

### PR Description
This PR adds functionality to be able to automatically generate query and mutation templates for selected data types or operations from the documentation and adds a setting to control the 'max depth' level of this nesting when adding a schema.

### What's changed
- Updated Query.vue to be able to display the query generated from the documentation.  
- Updated Sidebar.vue to be able to include a tab for getting queries from the documentation and a button to do so.  
- Updated settings.ts to contain a setting to set the maximum nesting depth for the queries generated from the documentation.  
- Updated DispatchingStore.ts slightly to enable dispatches to be able to work with the rest of the code.  
- Updated index.ts to be able to integrate the graphql schema templates and requests with the changes made to be able to get queries from the documentation.   
- Created queryBuilder.ts as a helper file to be able to generate a graphql query based on the documentation. Contains functions to generate and build the query.  
- Created har.ts to be able to parse the GQL request from the HoppGQLRequest and convert it to a HTTP Archive or HAR request.  
- Created index.ts to be able to use the HTTPSnippet library to make code snippets for the languages listed in codegenDefinitions from the HAR requests made through the har.ts file.

2024-10-27 06:40 UTC, Olly4k commented
The implementation looks good. However, I just want to check whether you've eliminated all of your local hosting changes. There seems to be some left over changes in the docker files that you should probably clean up.

2024-10-28 15:47 UTC, AndrewBastin requested changes

2024-10-28 15:47 UTC, AndrewBastin commented on docker-compose.deploy.yml
> +      POSTGRES_DB: test
Revert this change.

2024-10-28 15:47 UTC, AndrewBastin commented on packages/hoppscotch-data/src/graphql/index.ts
Revert this file back, the contents given here seems to be copied over from `hoppscotch-common`. `hoppscotch-data` changes should be backwards compatible (which this is not currently).

2024-12-18 08:51 UTC, closed without merging

2024-12-18 08:52 UTC, anwarulislam commented
This PR is incomplete and has invalid implementation. Following the issue in a different PR for a more accurate and complete solution. [#4626](https://github.com/hoppscotch/hoppscotch/pull/4626)