HSB-497 chore: user deletetion if not solo team owner
hoppscotch/hoppscotch pull request #4508
Opened 2024-11-03 04:15 UTC by mirarifhasan

Closes HSB-497

### What's changed

This PR updated the user deletion. Previously if a user a team owner, that user can not be deleted.
Now, a user can be deleted if he is not solo team owner in any of teams.

### Notes to reviewers

3 ways a user can be deleted.
1. User can delete himself
2. User can delete by admin
3. User can delete via API

2024-11-04 14:22 UTC, AndrewBastin requested changes

2024-11-04 14:22 UTC, AndrewBastin commented on packages/hoppscotch-backend/src/team/team.service.ts
> +      );
We can stop if we get a single match

2024-11-04 16:39 UTC, mirarifhasan commented on packages/hoppscotch-backend/src/team/team.service.ts
> +      );
Updated

2024-11-04 20:09 UTC, AndrewBastin approved these changes

2024-11-05 07:14 UTC, RaHehl commented
Would it be possible to control whether the workspace is deleted automatically when the last owner is removed, instead of blocking the deletion, through a configuration variable? This could make the behavior more flexible depending on the use case.

2024-11-05 07:15 UTC, RaHehl commented
Or perhaps even add a `force_delete` option for both the API and GUI to handle automatic workspace deletion when the last owner is removed?

2024-11-05 15:48 UTC, merged