hotfix: graphql connection error handler
hoppscotch/hoppscotch pull request #4523
Opened 2024-11-07 22:02 UTC by anwarulislam

This pull request fixes the error handling for GraphQL connections. It adds a new error message for HTTP errors and updates the connection state to "ERROR" when an HTTP error occurs.

2024-11-08 08:40 UTC, jamesgeorge007 requested changes
If the introspection attempt fails on the active endpoint with a non-Agent (given Agent is registered) interceptor, the `Connect` button goes to an infinite loading state.

2024-11-11 11:48 UTC, jamesgeorge007 requested changes
- The `Browser extension` is not installed and set as the active interceptor, the corresponding error state isn't displayed in the response section.

  ![image](https://github.com/user-attachments/assets/b52e964c-ef6c-4dac-9267-a3dbdb2823a7)

- For the error toast displayed when the introspection attempt fails while attempting to connect, we'll have to exclude it for the case when `Browser extension` is the active interceptor where the message displayed says `Heading not found`. Also, since a connection attempt is performed while sending a request, currently it results in an error toast due to the introspection query failing following a success toast saying the query succeeded in the given time frame and might not be necessary in such a case.

2024-11-11 16:32 UTC, jamesgeorge007 approved these changes

2024-11-12 13:10 UTC, AndrewBastin approved these changes

2024-11-12 15:45 UTC, merged