Add selected request path to test runner
hoppscotch/hoppscotch pull request #4609
Opened 2024-12-11 11:09 UTC by anwarulislam

This pull request adds the following changes:

- Added the `selectedRequestPath` property to the `HoppTestRunnerDocument` type.

- Modified the request item template to highlight the selected request.

- Added the `isLoading` flag to indicate when the tests are running.

- Updated the `runTests` function to set the `isLoading` flag.

- Modified the `selectRequest` function to emit the selected request path.

2024-12-18 11:12 UTC, nivedin requested changes

2024-12-18 17:51 UTC, jamesgeorge007 requested changes
Request headers displayed while selecting a request from a collection run should include the entries inherited from the parent collection level.

2024-12-19 14:36 UTC, nivedin approved these changes

2024-12-19 14:36 UTC, merged

2024-12-19 14:37 UTC, jamesgeorge007 commented on packages/hoppscotch-common/src/components/http/test/Runner.vue
> +        :text="`${t('collection_runner.response_body_lost_rerun')}`"
To be tracked separately.