chore: update collection runner modal UI
hoppscotch/hoppscotch pull request #4618
Opened 2024-12-16 08:58 UTC by nivedin

Closes HFE-669

### What's changed
This PR updates the collection runner modal UI
- Remove the padding and add a full width
- Move wiki button in the action slot of the tabs and add link w.r.t the tab state.

2024-12-16 09:05 UTC, liyasthomas commented on packages/hoppscotch-common/src/components/http/test/RunnerModal.vue
> +            :to="`https://docs.hoppscotch.io/documentation/${runnerLink}`"
No need to contact strings here. You could just pass the entire string from `runnerLink`.

2024-12-16 09:24 UTC, liyasthomas commented on packages/hoppscotch-common/src/components/http/test/RunnerModal.vue
> +const activeTab = ref<"test-runner" | "cli">("test-runner")
Let's just call `gui` and `cli` instead of `test-runner` and `cli`

2024-12-16 09:25 UTC, liyasthomas requested changes
Add my few comments.

2024-12-18 11:06 UTC, jamesgeorge007 approved these changes

2024-12-18 11:24 UTC, liyasthomas approved these changes

2024-12-18 11:59 UTC, merged