feat: graphql query generation from docs
hoppscotch/hoppscotch pull request #4626
Opened 2024-12-18 08:50 UTC by anwarulislam

Added feature to generate GraphQL queries from documentation.

2024-12-20 06:45 UTC, anwarulislam commented
Note to reviewer:  
Please skip the following files during your review. The intention was to revamp the entire documentation section, as the current version does not provide a better user experience. However, it requires more time, so we are pausing it for now. We will need these integrations later on.

Files:
- DocExplorer.vue
- ExplorerSection.vue
- SchemaBrowser.vue
- TypeLinkNew.vue
- explorer.ts

2024-12-20 08:25 UTC, jamesgeorge007 requested changes
- While inserting query documents, fields with subselection should be populated alongside placeholders for arguments.

  https://github.com/user-attachments/assets/91d721aa-21c0-468e-9fdb-0259c886a465

- While inserting multiple queries, the fields for the latter aren't populated correctly.

  https://github.com/user-attachments/assets/85a34346-ac37-450b-a735-df0f707e46a6

- An invalid attempt to insert arguments without the parent-level field crashes the page. Also, a schema failure for the tab state is reported against the key `gqlTabState` within local storage.

  https://github.com/user-attachments/assets/e32732e5-dc80-4ade-b50b-a7fa459fce84

- Inserting multiple top-level subscription fields should be prevented.

  https://github.com/user-attachments/assets/fd7826d2-9d4a-4a54-81e7-dc5b63864491

- The current placement of the insert field action leads to layout shifts and flickers at times. Keeping it towards the right end might be better when hovering over the node.

  https://github.com/user-attachments/assets/eb0e865c-b0e3-4ec4-8ae2-925d25982b00

2025-01-23 11:12 UTC, nivedin requested changes
https://github.com/user-attachments/assets/06d1f6bd-59e5-49d5-94b3-e6f8492eaa01

While switching tabs the documentation does not get updated if there is a selection before

- There are i18n strings to be added

- https://github.com/user-attachments/assets/9e35f4a5-0da3-4779-84c4-6dfac399b076

	We can show a visual representation if item is selected

2025-01-23 11:12 UTC, nivedin commented on packages/hoppscotch-common/src/components/graphql/Arguments.vue
> +        Show Deprecated Arguments
we can add this as i18n

2025-01-28 11:13 UTC, nivedin requested changes
when adding arguments can we do the similar approach that we show the active and non-active state for fields.

https://github.com/user-attachments/assets/73c73391-d87f-4336-ac51-dd7a0ec46c96

2025-01-28 11:14 UTC, nivedin commented
@anwarulislam do we need to add all the arguments when selecting a field ?

2025-01-28 15:45 UTC, anwarulislam commented
> @anwarulislam do we need to add all the arguments when selecting a field ?

Actually, we will automatically add arguments. However, users can remove them by clicking on the argument in the doc explorer.

2025-01-29 05:00 UTC, anwarulislam commented
> @anwarulislam do we need to add all the arguments when selecting a field ?

@nivedin I attempted to implement this, but I believe we can include it in a point release. For now, it will take a little time. It would be great if you have any workaround!

2025-01-29 09:08 UTC, nivedin commented
> > @anwarulislam do we need to add all the arguments when selecting a field ?
> 
> @nivedin I attempted to implement this, but I believe we can include it in a point release. For now, it will take a little time. It would be great if you have any workaround!

sure we can differ this flow for the point release then, what about the argument field addition state icon change

2025-01-29 09:11 UTC, anwarulislam commented
@Nivedin, I apologize for replying to the wrong comment. I was actually referring to postponing the functionality of changing the argument state.

2025-01-29 09:21 UTC, jamesgeorge007 requested changes
Toggling the preference while populating a GQL subscription document causes the page to crash. Although this is less likely to happen in production, it will affect the flow.

  https://github.com/user-attachments/assets/4f31084f-125b-4683-84d6-46893ff164be

> The generated document also gets into an invalid state at times.

  https://github.com/user-attachments/assets/fe1ced9d-f55c-4b7d-b8ba-7fc622e5339a

- There's a corner case when choosing fields under a type that causes the GQL document generated to become invalid.

  https://github.com/user-attachments/assets/6def1c34-9d7e-4c44-b118-de9359796e36

2025-01-30 05:44 UTC, jamesgeorge007 approved these changes
Although the issue's intensity with GQL documents being generated in an invalid state has reduced, it persists, especially with subscriptions; it can be revisited.

2025-01-30 05:45 UTC, merged